import { z } from 'zod/v4'
import {
  imageProjectResponseSchema,
  publicMediaJobEventPageSchema,
  mediaIdSchema,
} from './media.js'
import {
  imageCanvasCommandResponseSchema,
  imageCanvasPreflightResponseSchema,
  imageCanvasRenderResponseSchema,
  imageCanvasRevisionSchema,
  imageCanvasCommandRequestInputSchema,
  imageCanvasCreateInputSchema,
  imageCanvasPreflightInputSchema,
  imageCanvasRenderInputSchema,
  imageCandidateAdoptionResponseSchema,
  imageCandidateDecisionResponseSchema,
  imageCandidateDerivationResponseSchema,
  imageCreativePlanResponseSchema,
  imageDeliverySetSchema,
  imageDeliverySpecRevisionInputSchema,
  imageDeliverySpecRevisionResponseSchema,
  imageDerivationEstimateResponseSchema,
  imageExportResponseSchema,
  imageExportInputSchema,
  imageGenerationCancelResponseSchema,
  imageGenerationRoundEstimateResponseSchema,
  imageGenerationRoundResponseSchema,
  imageReferenceControlResponseSchema,
  adoptImageCandidateInputSchema,
  createCreativePlanInputSchema,
  createGenerationRoundInputSchema,
  decideImageCandidateInputSchema,
  deriveImageCandidateInputSchema,
  estimateDeriveImageCandidateInputSchema,
  estimateGenerationRoundInputSchema,
  publicImageCandidateGroupSchema,
  updateImageReferenceControlInputSchema,
} from './imageGeneration.js'
import {
  addImageWorkflowReferencesInputSchema,
  applyImageBriefOverridesInputSchema,
  cancelImageCampaignInputSchema,
  compileImageBriefResponseSchema,
  confirmImageCampaignInputSchema,
  createImageAssetGrantInputSchema,
  createImageBrandKitInputSchema,
  createImageCampaignInputSchema,
  createImageTemplateInputSchema,
  deleteImageReusableAggregateInputSchema,
  estimateImageCampaignInputSchema,
  imageAssetGrantListResponseSchema,
  imageAssetGrantResponseSchema,
  imageBrandKitListResponseSchema,
  imageBrandKitResponseSchema,
  imageCandidatePreviewResponseSchema,
  imageCampaignConfirmationResponseSchema,
  imageCampaignEstimateResponseSchema,
  imageCampaignListInputSchema,
  imageCampaignListResponseSchema,
  imageCampaignResponseSchema,
  imageInspirationBoardReadResponseSchema,
  imageInspirationBoardResponseSchema,
  imageProjectLibrarySchema,
  imageQuickCreateInputSchema,
  imageQuickCreateResponseSchema,
  imageTemplateListResponseSchema,
  imageTemplateResponseSchema,
  imageWorkbenchProjectListResponseSchema,
  imageWorkbenchProjectProjectionSchema,
  imageWorkflowProjectResponseSchema,
  promoteImageInspirationItemInputSchema,
  removeImageWorkflowReferenceInputSchema,
  replaceImageCampaignItemsInputSchema,
  reviseImageBrandKitInputSchema,
  reviseImageTemplateInputSchema,
  revokeImageAssetGrantInputSchema,
  retryImageCampaignItemInputSchema,
  startImageCampaignInputSchema,
  upsertImageInspirationItemsInputSchema,
} from './imageWorkflow.js'

const emptyPayloadSchema = z.object({}).strict()
const projectIdPayloadSchema = z.object({ projectId: mediaIdSchema }).strict()

export const imageWorkbenchIpcPayloadSchemas = {
  listProjects: emptyPayloadSchema,
  getProject: projectIdPayloadSchema,
  getProjectProjection: projectIdPayloadSchema,
  listOperationEvents: z.object({
    projectId: mediaIdSchema,
    cursor: z.number().int().nonnegative(),
    limit: z.number().int().min(1).max(200).optional(),
    waitMs: z.number().int().min(0).max(25_000).optional(),
  }).strict(),
  quickCreate: z.object({ input: imageQuickCreateInputSchema }).strict(),
  compileBrief: projectIdPayloadSchema,
  applyBriefOverrides: z.object({
    projectId: mediaIdSchema,
    briefId: mediaIdSchema,
    input: applyImageBriefOverridesInputSchema,
  }).strict(),
  getInspirationBoard: projectIdPayloadSchema,
  upsertInspirationItems: z.object({ projectId: mediaIdSchema, input: upsertImageInspirationItemsInputSchema }).strict(),
  promoteInspirationItem: z.object({
    projectId: mediaIdSchema,
    inspirationItemId: mediaIdSchema,
    input: promoteImageInspirationItemInputSchema,
  }).strict(),
  addReferences: z.object({ projectId: mediaIdSchema, input: addImageWorkflowReferencesInputSchema }).strict(),
  removeReference: z.object({
    projectId: mediaIdSchema,
    referenceId: mediaIdSchema,
    input: removeImageWorkflowReferenceInputSchema,
  }).strict(),
  updateReferenceControl: z.object({
    projectId: mediaIdSchema,
    referenceId: mediaIdSchema,
    input: updateImageReferenceControlInputSchema,
  }).strict(),
  createCreativePlan: z.object({ projectId: mediaIdSchema, input: createCreativePlanInputSchema }).strict(),
  estimateGenerationRound: z.object({ projectId: mediaIdSchema, input: estimateGenerationRoundInputSchema }).strict(),
  createGenerationRound: z.object({ projectId: mediaIdSchema, input: createGenerationRoundInputSchema }).strict(),
  getCandidateGroup: z.object({ projectId: mediaIdSchema, candidateGroupId: mediaIdSchema }).strict(),
  getCandidatePreview: z.object({ projectId: mediaIdSchema, candidateId: mediaIdSchema }).strict(),
  decideCandidate: z.object({ projectId: mediaIdSchema, candidateId: mediaIdSchema, input: decideImageCandidateInputSchema }).strict(),
  estimateCandidateDerivation: z.object({ projectId: mediaIdSchema, candidateId: mediaIdSchema, input: estimateDeriveImageCandidateInputSchema }).strict(),
  deriveCandidate: z.object({ projectId: mediaIdSchema, candidateId: mediaIdSchema, input: deriveImageCandidateInputSchema }).strict(),
  adoptCandidate: z.object({ projectId: mediaIdSchema, candidateId: mediaIdSchema, input: adoptImageCandidateInputSchema }).strict(),
  cancelOperation: z.object({ projectId: mediaIdSchema, operationId: mediaIdSchema }).strict(),
  listCanvases: projectIdPayloadSchema,
  getCanvas: z.object({ projectId: mediaIdSchema, canvasId: mediaIdSchema, revision: z.number().int().nonnegative().optional() }).strict(),
  createCanvas: z.object({ projectId: mediaIdSchema, input: imageCanvasCreateInputSchema }).strict(),
  applyCanvasCommand: z.object({ projectId: mediaIdSchema, canvasId: mediaIdSchema, input: imageCanvasCommandRequestInputSchema }).strict(),
  preflightCanvas: z.object({ projectId: mediaIdSchema, canvasId: mediaIdSchema, input: imageCanvasPreflightInputSchema }).strict(),
  renderCanvas: z.object({ projectId: mediaIdSchema, canvasId: mediaIdSchema, input: imageCanvasRenderInputSchema }).strict(),
  createDeliverySpec: z.object({ projectId: mediaIdSchema, input: imageDeliverySpecRevisionInputSchema }).strict(),
  exportDelivery: z.object({ projectId: mediaIdSchema, input: imageExportInputSchema }).strict(),
  getDeliverySet: z.object({ projectId: mediaIdSchema, deliverySetId: mediaIdSchema }).strict(),
  getProjectLibrary: projectIdPayloadSchema,
  listBrandKits: emptyPayloadSchema,
  getBrandKit: z.object({ brandKitId: mediaIdSchema }).strict(),
  createBrandKit: z.object({ input: createImageBrandKitInputSchema }).strict(),
  reviseBrandKit: z.object({ brandKitId: mediaIdSchema, input: reviseImageBrandKitInputSchema }).strict(),
  deleteBrandKit: z.object({ brandKitId: mediaIdSchema, input: deleteImageReusableAggregateInputSchema }).strict(),
  listTemplates: emptyPayloadSchema,
  getTemplate: z.object({ templateId: mediaIdSchema }).strict(),
  createTemplate: z.object({ input: createImageTemplateInputSchema }).strict(),
  reviseTemplate: z.object({ templateId: mediaIdSchema, input: reviseImageTemplateInputSchema }).strict(),
  deleteTemplate: z.object({ templateId: mediaIdSchema, input: deleteImageReusableAggregateInputSchema }).strict(),
  createAssetGrant: z.object({ input: createImageAssetGrantInputSchema }).strict(),
  revokeAssetGrant: z.object({ grantId: mediaIdSchema, input: revokeImageAssetGrantInputSchema }).strict(),
  listAssetGrants: emptyPayloadSchema,
  listCampaigns: z.object({ input: imageCampaignListInputSchema.optional() }).strict(),
  getCampaign: z.object({ campaignId: mediaIdSchema }).strict(),
  createCampaign: z.object({ input: createImageCampaignInputSchema }).strict(),
  replaceCampaignItems: z.object({ campaignId: mediaIdSchema, input: replaceImageCampaignItemsInputSchema }).strict(),
  estimateCampaign: z.object({ campaignId: mediaIdSchema, input: estimateImageCampaignInputSchema }).strict(),
  confirmCampaign: z.object({ campaignId: mediaIdSchema, input: confirmImageCampaignInputSchema }).strict(),
  confirmCampaignRetry: z.object({ campaignId: mediaIdSchema, itemId: mediaIdSchema, input: confirmImageCampaignInputSchema }).strict(),
  startCampaign: z.object({ campaignId: mediaIdSchema, input: startImageCampaignInputSchema }).strict(),
  cancelCampaign: z.object({ campaignId: mediaIdSchema, input: cancelImageCampaignInputSchema }).strict(),
  retryCampaignItem: z.object({ campaignId: mediaIdSchema, itemId: mediaIdSchema, input: retryImageCampaignItemInputSchema }).strict(),
} as const

export const imageWorkbenchIpcRequestSchema = z.union([
  z.object({ method: z.literal('listProjects'), payload: imageWorkbenchIpcPayloadSchemas.listProjects }),
  z.object({ method: z.literal('getProject'), payload: imageWorkbenchIpcPayloadSchemas.getProject }),
  z.object({ method: z.literal('getProjectProjection'), payload: imageWorkbenchIpcPayloadSchemas.getProjectProjection }),
  z.object({ method: z.literal('listOperationEvents'), payload: imageWorkbenchIpcPayloadSchemas.listOperationEvents }),
  z.object({ method: z.literal('quickCreate'), payload: imageWorkbenchIpcPayloadSchemas.quickCreate }),
  z.object({ method: z.literal('compileBrief'), payload: imageWorkbenchIpcPayloadSchemas.compileBrief }),
  z.object({ method: z.literal('applyBriefOverrides'), payload: imageWorkbenchIpcPayloadSchemas.applyBriefOverrides }),
  z.object({ method: z.literal('getInspirationBoard'), payload: imageWorkbenchIpcPayloadSchemas.getInspirationBoard }),
  z.object({ method: z.literal('upsertInspirationItems'), payload: imageWorkbenchIpcPayloadSchemas.upsertInspirationItems }),
  z.object({ method: z.literal('promoteInspirationItem'), payload: imageWorkbenchIpcPayloadSchemas.promoteInspirationItem }),
  z.object({ method: z.literal('addReferences'), payload: imageWorkbenchIpcPayloadSchemas.addReferences }),
  z.object({ method: z.literal('removeReference'), payload: imageWorkbenchIpcPayloadSchemas.removeReference }),
  z.object({ method: z.literal('updateReferenceControl'), payload: imageWorkbenchIpcPayloadSchemas.updateReferenceControl }),
  z.object({ method: z.literal('createCreativePlan'), payload: imageWorkbenchIpcPayloadSchemas.createCreativePlan }),
  z.object({ method: z.literal('estimateGenerationRound'), payload: imageWorkbenchIpcPayloadSchemas.estimateGenerationRound }),
  z.object({ method: z.literal('createGenerationRound'), payload: imageWorkbenchIpcPayloadSchemas.createGenerationRound }),
  z.object({ method: z.literal('getCandidateGroup'), payload: imageWorkbenchIpcPayloadSchemas.getCandidateGroup }),
  z.object({ method: z.literal('getCandidatePreview'), payload: imageWorkbenchIpcPayloadSchemas.getCandidatePreview }),
  z.object({ method: z.literal('decideCandidate'), payload: imageWorkbenchIpcPayloadSchemas.decideCandidate }),
  z.object({ method: z.literal('estimateCandidateDerivation'), payload: imageWorkbenchIpcPayloadSchemas.estimateCandidateDerivation }),
  z.object({ method: z.literal('deriveCandidate'), payload: imageWorkbenchIpcPayloadSchemas.deriveCandidate }),
  z.object({ method: z.literal('adoptCandidate'), payload: imageWorkbenchIpcPayloadSchemas.adoptCandidate }),
  z.object({ method: z.literal('cancelOperation'), payload: imageWorkbenchIpcPayloadSchemas.cancelOperation }),
  z.object({ method: z.literal('listCanvases'), payload: imageWorkbenchIpcPayloadSchemas.listCanvases }),
  z.object({ method: z.literal('getCanvas'), payload: imageWorkbenchIpcPayloadSchemas.getCanvas }),
  z.object({ method: z.literal('createCanvas'), payload: imageWorkbenchIpcPayloadSchemas.createCanvas }),
  z.object({ method: z.literal('applyCanvasCommand'), payload: imageWorkbenchIpcPayloadSchemas.applyCanvasCommand }),
  z.object({ method: z.literal('preflightCanvas'), payload: imageWorkbenchIpcPayloadSchemas.preflightCanvas }),
  z.object({ method: z.literal('renderCanvas'), payload: imageWorkbenchIpcPayloadSchemas.renderCanvas }),
  z.object({ method: z.literal('createDeliverySpec'), payload: imageWorkbenchIpcPayloadSchemas.createDeliverySpec }),
  z.object({ method: z.literal('exportDelivery'), payload: imageWorkbenchIpcPayloadSchemas.exportDelivery }),
  z.object({ method: z.literal('getDeliverySet'), payload: imageWorkbenchIpcPayloadSchemas.getDeliverySet }),
  z.object({ method: z.literal('getProjectLibrary'), payload: imageWorkbenchIpcPayloadSchemas.getProjectLibrary }),
  z.object({ method: z.literal('listBrandKits'), payload: imageWorkbenchIpcPayloadSchemas.listBrandKits }),
  z.object({ method: z.literal('getBrandKit'), payload: imageWorkbenchIpcPayloadSchemas.getBrandKit }),
  z.object({ method: z.literal('createBrandKit'), payload: imageWorkbenchIpcPayloadSchemas.createBrandKit }),
  z.object({ method: z.literal('reviseBrandKit'), payload: imageWorkbenchIpcPayloadSchemas.reviseBrandKit }),
  z.object({ method: z.literal('deleteBrandKit'), payload: imageWorkbenchIpcPayloadSchemas.deleteBrandKit }),
  z.object({ method: z.literal('listTemplates'), payload: imageWorkbenchIpcPayloadSchemas.listTemplates }),
  z.object({ method: z.literal('getTemplate'), payload: imageWorkbenchIpcPayloadSchemas.getTemplate }),
  z.object({ method: z.literal('createTemplate'), payload: imageWorkbenchIpcPayloadSchemas.createTemplate }),
  z.object({ method: z.literal('reviseTemplate'), payload: imageWorkbenchIpcPayloadSchemas.reviseTemplate }),
  z.object({ method: z.literal('deleteTemplate'), payload: imageWorkbenchIpcPayloadSchemas.deleteTemplate }),
  z.object({ method: z.literal('createAssetGrant'), payload: imageWorkbenchIpcPayloadSchemas.createAssetGrant }),
  z.object({ method: z.literal('revokeAssetGrant'), payload: imageWorkbenchIpcPayloadSchemas.revokeAssetGrant }),
  z.object({ method: z.literal('listAssetGrants'), payload: imageWorkbenchIpcPayloadSchemas.listAssetGrants }),
  z.object({ method: z.literal('listCampaigns'), payload: imageWorkbenchIpcPayloadSchemas.listCampaigns }),
  z.object({ method: z.literal('getCampaign'), payload: imageWorkbenchIpcPayloadSchemas.getCampaign }),
  z.object({ method: z.literal('createCampaign'), payload: imageWorkbenchIpcPayloadSchemas.createCampaign }),
  z.object({ method: z.literal('replaceCampaignItems'), payload: imageWorkbenchIpcPayloadSchemas.replaceCampaignItems }),
  z.object({ method: z.literal('estimateCampaign'), payload: imageWorkbenchIpcPayloadSchemas.estimateCampaign }),
  z.object({ method: z.literal('confirmCampaign'), payload: imageWorkbenchIpcPayloadSchemas.confirmCampaign }),
  z.object({ method: z.literal('confirmCampaignRetry'), payload: imageWorkbenchIpcPayloadSchemas.confirmCampaignRetry }),
  z.object({ method: z.literal('startCampaign'), payload: imageWorkbenchIpcPayloadSchemas.startCampaign }),
  z.object({ method: z.literal('cancelCampaign'), payload: imageWorkbenchIpcPayloadSchemas.cancelCampaign }),
  z.object({ method: z.literal('retryCampaignItem'), payload: imageWorkbenchIpcPayloadSchemas.retryCampaignItem }),
])

export const imageWorkbenchIpcPayloadSchema = imageWorkbenchIpcRequestSchema

export function parseImageWorkbenchIpcRequest(value: unknown): ImageWorkbenchIpcRequest {
  return imageWorkbenchIpcRequestSchema.parse(value)
}

export const imageWorkbenchIpcResponseSchemas = {
  listProjects: imageWorkbenchProjectListResponseSchema,
  getProject: imageProjectResponseSchema,
  getProjectProjection: imageWorkbenchProjectProjectionSchema,
  listOperationEvents: publicMediaJobEventPageSchema,
  quickCreate: imageQuickCreateResponseSchema,
  compileBrief: compileImageBriefResponseSchema,
  applyBriefOverrides: imageWorkflowProjectResponseSchema,
  getInspirationBoard: imageInspirationBoardReadResponseSchema,
  upsertInspirationItems: imageInspirationBoardResponseSchema,
  promoteInspirationItem: imageInspirationBoardResponseSchema,
  addReferences: imageWorkflowProjectResponseSchema,
  removeReference: imageWorkflowProjectResponseSchema,
  updateReferenceControl: imageReferenceControlResponseSchema,
  createCreativePlan: imageCreativePlanResponseSchema,
  estimateGenerationRound: imageGenerationRoundEstimateResponseSchema,
  createGenerationRound: imageGenerationRoundResponseSchema,
  getCandidateGroup: z.object({ candidate_group: publicImageCandidateGroupSchema }).strict(),
  getCandidatePreview: imageCandidatePreviewResponseSchema,
  decideCandidate: imageCandidateDecisionResponseSchema,
  estimateCandidateDerivation: imageDerivationEstimateResponseSchema,
  deriveCandidate: imageCandidateDerivationResponseSchema,
  adoptCandidate: imageCandidateAdoptionResponseSchema,
  cancelOperation: imageGenerationCancelResponseSchema,
  listCanvases: z.object({ canvases: z.array(imageCanvasRevisionSchema).max(512) }).strict(),
  getCanvas: z.object({ canvas: imageCanvasRevisionSchema }).strict(),
  createCanvas: imageCanvasCommandResponseSchema,
  applyCanvasCommand: imageCanvasCommandResponseSchema,
  preflightCanvas: imageCanvasPreflightResponseSchema,
  renderCanvas: imageCanvasRenderResponseSchema,
  createDeliverySpec: imageDeliverySpecRevisionResponseSchema,
  exportDelivery: imageExportResponseSchema,
  getDeliverySet: z.object({ delivery_set: imageDeliverySetSchema }).strict(),
  getProjectLibrary: imageProjectLibrarySchema,
  listBrandKits: imageBrandKitListResponseSchema,
  getBrandKit: imageBrandKitResponseSchema,
  createBrandKit: imageBrandKitResponseSchema,
  reviseBrandKit: imageBrandKitResponseSchema,
  deleteBrandKit: imageBrandKitResponseSchema,
  listTemplates: imageTemplateListResponseSchema,
  getTemplate: imageTemplateResponseSchema,
  createTemplate: imageTemplateResponseSchema,
  reviseTemplate: imageTemplateResponseSchema,
  deleteTemplate: imageTemplateResponseSchema,
  createAssetGrant: imageAssetGrantResponseSchema,
  revokeAssetGrant: imageAssetGrantResponseSchema,
  listAssetGrants: imageAssetGrantListResponseSchema,
  listCampaigns: imageCampaignListResponseSchema,
  getCampaign: imageCampaignResponseSchema,
  createCampaign: imageCampaignResponseSchema,
  replaceCampaignItems: imageCampaignResponseSchema,
  estimateCampaign: imageCampaignEstimateResponseSchema,
  confirmCampaign: imageCampaignConfirmationResponseSchema,
  confirmCampaignRetry: imageCampaignConfirmationResponseSchema,
  startCampaign: imageCampaignResponseSchema,
  cancelCampaign: imageCampaignResponseSchema,
  retryCampaignItem: imageCampaignResponseSchema,
} as const

export type ImageWorkbenchIpcMethod = keyof typeof imageWorkbenchIpcPayloadSchemas
export type ImageWorkbenchIpcPayloadByMethod = {
  [Method in ImageWorkbenchIpcMethod]: z.input<(typeof imageWorkbenchIpcPayloadSchemas)[Method]>
}
export type ImageWorkbenchIpcValueByMethod = {
  [Method in ImageWorkbenchIpcMethod]: z.infer<(typeof imageWorkbenchIpcResponseSchemas)[Method]>
}
export type ImageWorkbenchIpcRequest = z.infer<typeof imageWorkbenchIpcRequestSchema>

export type {
  ImageWorkbenchIpcPayloadByMethod as ImageWorkbenchIpcInputs,
  ImageWorkbenchIpcValueByMethod as ImageWorkbenchIpcOutputs,
}
