import { expect, test } from 'bun:test'
import { createGatewayFetch, MemoryUsageStore } from './app'
import { gatewayTestAccessTokenFor, gatewayTestAuthority } from './auth/testFixture'

type Upstream = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>
const config = (extra: Record<string, string | undefined> = {}) => ({ GW_RELAY_TOKEN: 'relay', GW_DEEPSEEK_KEY: 'key', GW_DEEPSEEK_BASE: 'https://deepseek.example', GW_DEEPSEEK_CONC: '4', GW_DEEPSEEK_USER_CONC: '2', GW_DEEPSEEK_TOKEN_CONC: '4', GW_DEEPSEEK_QUEUE_MAX: '120', GW_DEEPSEEK_QUEUE_MAX_WAIT: '10', ...extra })
function request(identity: string, client: string, signal?: AbortSignal) { return new Request('http://local/v1/chat/completions', { method: 'POST', signal, headers: { Authorization: `Bearer ${gatewayTestAccessTokenFor(identity)}`, 'Content-Type': 'application/json', 'X-BB-Installation-ID': client, 'X-BB-Provider-Protocol': 'bb-provider-gateway/1.0' }, body: JSON.stringify({ model: 'deepseek-v4-flash', stream: true }) }) }
function app(upstream: Upstream, extra: Record<string, string | undefined> = {}) {
  const fetch = createGatewayFetch({ authority: gatewayTestAuthority, env: config(extra), usageStore: new MemoryUsageStore(), transcribeImpl: null, fetchImpl: upstream })
  return { fetch, async drain(response: Response) { try { await response.text() } catch {} }, async capacity() { const res = await fetch(new Request('http://local/healthz', { headers: { Authorization: `Bearer ${gatewayTestAccessTokenFor('capacity-health')}` } })); return (await res.json()).capacity.deepseek as { active: number; queued: number } } }
}
const wait = () => new Promise(resolve => setTimeout(resolve, 25))
function gate() { let released = false, calls = 0, active = 0, peak = 0; const waiters: Array<() => void> = []; const upstream: Upstream = async () => { calls++; active++; peak = Math.max(peak, active); await new Promise<void>(resolve => released ? resolve() : waiters.push(resolve)); active--; return new Response('data: done\n\n', { headers: { 'content-type': 'text/event-stream' } }) }; return { upstream, stats: () => ({ calls, active, peak }), release: () => { released = true; waiters.splice(0).forEach(resolve => resolve()) } } }
async function expectDrained(instance: ReturnType<typeof app>) { await wait(); expect(await instance.capacity()).toMatchObject({ active: 0, queued: 0 }) }

test('100 installations use 100 actual bearer identities and respect global DeepSeek capacity', async () => {
  const g = gate(), instance = app(g.upstream, { GW_DEEPSEEK_QUEUE_MAX: '100' }); const requests = Array.from({ length: 100 }, (_, i) => instance.fetch(request(`capacity-${i}`, `client-${i}`)))
  await wait(); expect(g.stats()).toMatchObject({ calls: 4, peak: 4 }); g.release(); await Promise.all(requests.map(async pending => { const response = await pending; expect(response.status).toBe(200); await instance.drain(response) })); await expectDrained(instance)
}, { timeout: 20_000 })
test('one bearer five requests is capped at owner concurrency two and then drains', async () => {
  const g = gate(), instance = app(g.upstream, { GW_DEEPSEEK_CONC: '5', GW_DEEPSEEK_USER_CONC: '2', GW_DEEPSEEK_TOKEN_CONC: '5' }); const requests = Array.from({ length: 5 }, () => instance.fetch(request('same-owner', 'same-owner')))
  await wait(); expect(g.stats()).toMatchObject({ calls: 2, peak: 2 }); g.release(); await Promise.all(requests.map(async pending => { const response = await pending; expect(response.status).toBe(200); await instance.drain(response) })); await expectDrained(instance)
})
test('different bearer enters while first bearer owns queued work', async () => {
  const g = gate(), instance = app(g.upstream, { GW_DEEPSEEK_CONC: '3', GW_DEEPSEEK_USER_CONC: '1', GW_DEEPSEEK_TOKEN_CONC: '2' }); const a = [instance.fetch(request('principal-a', 'a')), instance.fetch(request('principal-a', 'a')), instance.fetch(request('principal-a', 'a'))]; await wait(); const b = instance.fetch(request('principal-b', 'b1')); await wait(); expect(g.stats().calls).toBe(2); g.release(); await Promise.all([...a, b].map(async pending => { const response = await pending; expect(response.status).toBe(200); await instance.drain(response) })); await expectDrained(instance)
})
test('connection error retries once and drains', async () => { let calls = 0; const instance = app(async () => { calls++; throw new Error('offline') }); const response = await instance.fetch(request('connection-error', 'connection-error')); expect(response.status).toBe(502); expect(calls).toBe(2); await expectDrained(instance) })
test('continuous 5xx retries once then drains', async () => { let calls = 0; const instance = app(async () => { calls++; return new Response('boom', { status: 503 }) }); const response = await instance.fetch(request('five-xx', 'five-xx')); expect(response.status).toBe(503); expect(calls).toBe(2); await expectDrained(instance) })
test('429 is single-call and drains', async () => { let calls = 0; const instance = app(async () => { calls++; return new Response('busy', { status: 429 }) }); const response = await instance.fetch(request('rate-limit', 'rate-limit')); expect(response.status).toBe(429); expect(calls).toBe(1); await expectDrained(instance) })
test('midstream SSE error drains', async () => { let calls = 0; const instance = app(async () => { calls++; return new Response(new ReadableStream({ start(controller) { controller.enqueue(new TextEncoder().encode('data: partial\n\n')); controller.error(new Error('drop')) } }), { headers: { 'content-type': 'text/event-stream' } }) }); const response = await instance.fetch(request('midstream', 'midstream')); expect(response.status).toBe(200); await instance.drain(response); expect(calls).toBe(1); await expectDrained(instance) })
test('response body cancellation drains', async () => { const instance = app(async () => new Response(new ReadableStream({ start(controller) { controller.enqueue(new TextEncoder().encode('data: held\n\n')) } }), { headers: { 'content-type': 'text/event-stream' } })); const response = await instance.fetch(request('body-cancel', 'body-cancel')); await response.body!.cancel(); await expectDrained(instance) })
test('queue timeout drains', async () => { const g = gate(), instance = app(g.upstream, { GW_DEEPSEEK_CONC: '1', GW_DEEPSEEK_USER_CONC: '2', GW_DEEPSEEK_TOKEN_CONC: '2', GW_DEEPSEEK_QUEUE_MAX: '1', GW_DEEPSEEK_QUEUE_MAX_WAIT: '0.02' }); const first = instance.fetch(request('timeout-a', 'timeout-a')); await wait(); const timeout = await instance.fetch(request('timeout-b', 'timeout-b')); expect(timeout.status).toBe(429); g.release(); await instance.drain(await first); await expectDrained(instance) })
test('queued AbortSignal drains', async () => { const g = gate(), instance = app(g.upstream, { GW_DEEPSEEK_CONC: '1', GW_DEEPSEEK_USER_CONC: '2', GW_DEEPSEEK_TOKEN_CONC: '2', GW_DEEPSEEK_QUEUE_MAX: '1' }); const first = instance.fetch(request('abort-a', 'abort-a')); await wait(); const controller = new AbortController(), queued = instance.fetch(request('abort-b', 'abort-b', controller.signal)); controller.abort(); expect((await queued).status).toBe(499); g.release(); await instance.drain(await first); await expectDrained(instance) })
