import type { WorkbenchRole, TargetCustomerType, OutputPackageItem } from "@/types/generate";

export interface RoleTaskCard {
  id: string;
  role: WorkbenchRole;
  title: string;
  description: string;
  userIntentTemplate: string;
  targetCustomerType: TargetCustomerType;
  outputPackage: OutputPackageItem[];
  sceneTags: string[];
  requiredProfileModules: string[];
  priority: "P0" | "P1" | "P2";
  inputHints?: string[];
  /** 后端场景模板 key，如 "operation.old_customer_recall"。有 promptKey 时后端优先使用该模板，否则 fallback 到 workbench.free_intent。 */
  promptKey?: string;
}

/* ─── 店长 manager — 10 张卡片 ─── */

const MANAGER_TASKS: RoleTaskCard[] = [
  {
    id: "mgr-daily-moments",
    role: "manager",
    title: "今日朋友圈",
    description: "产出 1-2 条门店品牌朋友圈，体现门店定位和风格",
    userIntentTemplate: "帮我写一条今天的朋友圈，重点推一下门店氛围和台子状态",
    targetCustomerType: "all",
    outputPackage: ["moments", "execution_tips"],
    sceneTags: ["朋友圈", "日常", "门店品牌"],
    requiredProfileModules: ["content_style", "basic"],
    priority: "P0",
    promptKey: "copywriting.moments",
    inputHints: [
      "今天门店有什么可说的？比如空台、氛围、台子状态、天气。",
      "想发 1 条还是 2 条？语气要熟人自然还是品牌感一点？",
      "有没有不想写的内容？比如别写优惠、别写价格。",
    ],
  },
  {
    id: "mgr-old-customer-recall",
    role: "manager",
    title: "老客户回访",
    description: "熟人口吻私聊邀约老客户来打球，自然不骚扰",
    userIntentTemplate: "好久没联系老客户了，帮我发几句话约他们来打球，不要太刻意",
    targetCustomerType: "old",
    outputPackage: ["private_chat", "moments", "execution_tips"],
    sceneTags: ["老客户", "私聊", "回访", "邀约"],
    requiredProfileModules: ["customer_structure", "content_style"],
    priority: "P0",
    promptKey: "operation.old_customer_recall",
    inputHints: [
      "这批客户大概多久没来了？一周、半个月还是一个月？",
      "想生成私聊话术、朋友圈，还是两者都要？",
      "今天有没有空台、助教可约、周赛活动可以顺带提？",
      "语气要熟人一点，还是礼貌一点？",
    ],
  },
  {
    id: "mgr-member-group-notice",
    role: "manager",
    title: "会员群空台提醒",
    description: "会员群发空台促活通知，按本店实际情况发布",
    userIntentTemplate: "会员群发个空台提醒，让大家知道现在可以来打球，别写优惠",
    targetCustomerType: "old",
    outputPackage: ["group_notice", "private_chat", "execution_tips"],
    sceneTags: ["会员群", "空台", "促活"],
    requiredProfileModules: ["private_domain_groups", "commerce_rules"],
    priority: "P0",
    promptKey: "operation.group_content",
    inputHints: [
      "今天哪个时间段空台多？下午、晚上还是全天？",
      "要不要提醒会员提前说一声，方便留台？",
      "是否明确不写优惠、不写会员专属权益？",
    ],
  },
  {
    id: "mgr-competition-group-match",
    role: "manager",
    title: "竞技群约局通知",
    description: "竞技群组织约球，轻松口吻，表达自然边界清晰",
    userIntentTemplate: "竞技群发今晚约局通知，看看有没有人想打球",
    targetCustomerType: "competition",
    outputPackage: ["group_notice", "private_chat", "execution_tips"],
    sceneTags: ["竞技群", "约局", "撮合"],
    requiredProfileModules: ["private_domain_groups", "equipment"],
    priority: "P0",
    promptKey: "operation.group_content",
    inputHints: [
      "大概几点约？今晚、下午还是周末？",
      "是轻松约球、练球局，还是周赛前热身？",
      "门店有没有乔氏、斯诺克或指定桌型需要提？",
    ],
  },
  {
    id: "mgr-assistant-promo",
    role: "manager",
    title: "助教到店推广",
    description: "朋友圈/群公告推广助教服务，专业表达",
    userIntentTemplate: "今天助教都在店里，帮我发条朋友圈让客户知道可以约助教服务",
    targetCustomerType: "assistant",
    outputPackage: ["moments", "group_notice", "execution_tips"],
    sceneTags: ["助教", "推广", "朋友圈"],
    requiredProfileModules: ["assistant_system"],
    priority: "P0",
    promptKey: "operation.assistant_promo",
    inputHints: [
      "是新助教到店，还是今日助教可约？",
      "想发朋友圈、群公告，还是私聊客户？",
      "助教偏服务体验型，还是技术陪练型？",
    ],
  },
  {
    id: "mgr-weekly-tournament-notice",
    role: "manager",
    title: "周赛活动通知",
    description: "周赛预热朋友圈+群公告+私聊邀约全套",
    userIntentTemplate: "这周周赛帮我发通知，朋友圈和群里都要，预热一下",
    targetCustomerType: "competition",
    outputPackage: ["moments", "group_notice", "private_chat", "execution_tips"],
    sceneTags: ["周赛", "活动", "赛事"],
    requiredProfileModules: ["events"],
    priority: "P0",
    promptKey: "operation.tournament",
    inputHints: [
      "周赛是今天、明天还是这周几？大概几点开始？",
      "想发朋友圈、群公告，还是私聊邀约？",
      "要不要提醒报名、赛制、到店时间或名额情况？",
    ],
  },
  {
    id: "mgr-staff-group-notice",
    role: "manager",
    title: "员工群通知",
    description: "员工群发提醒或通知，事项清楚适合下发",
    userIntentTemplate: "员工群发个提醒，让大家注意今天卫生和前厅接待",
    targetCustomerType: "all",
    outputPackage: ["group_notice", "execution_tips"],
    sceneTags: ["员工群", "管理", "SOP"],
    requiredProfileModules: ["private_domain_groups"],
    priority: "P1",
    promptKey: "copywriting.group_notice",
    inputHints: [
      "这条通知是提醒卫生、接待、排班，还是服务标准？",
      "需要写成群公告，还是内部执行清单？",
      "要不要明确时间、负责人和注意事项？",
    ],
  },
  {
    id: "mgr-daily-brief",
    role: "manager",
    title: "每日简报",
    description: "各岗位数据汇总+文字总结+明日计划",
    userIntentTemplate: "帮我写今天的店长日报，今天做了朋友圈推广、老客户回访、会员群空台提醒",
    targetCustomerType: "all",
    outputPackage: ["daily_report", "execution_tips"],
    sceneTags: ["日报", "管理", "汇报"],
    requiredProfileModules: ["business_goals"],
    priority: "P0",
    promptKey: "operation.daily_report",
    inputHints: [
      "今天想汇报哪些内容？人气、营收、助教、会员群还是竞技群？",
      "这份简报是发给老板看，还是发员工群？",
      "明天需要安排哪些重点工作？比如老客回访、助教预约、周赛报名。",
    ],
  },
  {
    id: "mgr-sports-event-watching",
    role: "manager",
    title: "看球活动",
    description: "世界杯/斯诺克等看球活动方案+宣传文案",
    userIntentTemplate: "最近有重要的体育赛事，帮我策划一个看球活动方案",
    targetCustomerType: "all",
    outputPackage: ["activity_plan", "moments", "group_notice", "poster_copy", "execution_tips"],
    sceneTags: ["看球", "活动", "赛事"],
    requiredProfileModules: ["events"],
    priority: "P2",
    promptKey: "operation.sports_event_watching",
    inputHints: [
      "什么赛事？世界杯、斯诺克世锦赛、还是其他？",
      "门店有电视/投影吗？能提供什么餐饮？",
      "想要活动方案、宣传文案，还是全套？",
    ],
  },
  {
    id: "mgr-staff-birthday",
    role: "manager",
    title: "员工/助教生日",
    description: "员工群祝福+助教生日朋友圈+福利通知",
    userIntentTemplate: "今天有员工生日，帮我写祝福文案和福利通知",
    targetCustomerType: "all",
    outputPackage: ["group_notice", "moments", "execution_tips"],
    sceneTags: ["生日", "关怀", "员工"],
    requiredProfileModules: [],
    priority: "P2",
    promptKey: "operation.staff_birthday",
    inputHints: [
      "是谁生日？员工还是助教？叫什么名字？",
      "想发员工群祝福、朋友圈，还是两者都要？",
      "门店有没有生日福利？没有就用占位。",
    ],
  },
  {
    id: "mgr-platform-review",
    role: "manager",
    title: "团购评分提升方案",
    description: "制定美团/抖音团购评分提升计划，从当前评分到目标评分的执行路径",
    userIntentTemplate: "帮我制定一个团购评分提升方案，我们目前评分需要提升",
    targetCustomerType: "groupbuy",
    outputPackage: ["execution_tips", "sop_checklist"],
    sceneTags: ["团购", "评分", "美团", "抖音"],
    requiredProfileModules: ["commerce_rules"],
    priority: "P1",
    promptKey: "operation.platform_review_plan",
    inputHints: [
      "目前在哪些平台做团购？美团、抖音还是都有？",
      "当前评分大概多少？目标是多少？",
    ],
  },
  {
    id: "mgr-groupbuy-optimize",
    role: "manager",
    title: "团购品类优化",
    description: "精简团购品类，设计爆款商品，优化价格策略",
    userIntentTemplate: "帮我优化一下团购品类设计，现在品类太多太杂了",
    targetCustomerType: "groupbuy",
    outputPackage: ["execution_tips"],
    sceneTags: ["团购", "品类", "爆款", "定价"],
    requiredProfileModules: ["commerce_rules"],
    priority: "P1",
    promptKey: "operation.groupbuy_optimize",
    inputHints: [
      "目前有几个团购品类？哪个卖得最好？",
      "引流区的价格是多少？",
    ],
  },
];

/* ─── 助教管理 assistant_manager — 12 张卡片 ─── */

const ASSISTANT_MANAGER_TASKS: RoleTaskCard[] = [
  {
    id: "am-today-available",
    role: "assistant_manager",
    title: "今日助教可约通知",
    description: "朋友圈/群公告告知助教可约，专业表达",
    userIntentTemplate: "今天助教都在，帮我发个朋友圈让客户知道可以约助教服务",
    targetCustomerType: "assistant",
    outputPackage: ["moments", "execution_tips"],
    sceneTags: ["助教", "朋友圈", "预约"],
    requiredProfileModules: ["assistant_system"],
    priority: "P0",
    promptKey: "operation.assistant_promo",
    inputHints: [
      "今天哪些时间段可约？下午、晚上还是指定时段？",
      "是发朋友圈、助教客户群，还是私聊客户？",
      "要不要强调提前预约，避免客户白跑？",
    ],
  },
  {
    id: "am-new-assistant-notice",
    role: "assistant_manager",
    title: "新助教到店",
    description: "专业推广新助教服务体验，表达得体",
    userIntentTemplate: "新助教到店了，帮我写一个朋友圈和群公告，让大家知道新助教可以约了",
    targetCustomerType: "assistant",
    outputPackage: ["moments", "group_notice", "execution_tips"],
    sceneTags: ["助教", "新助教", "推广"],
    requiredProfileModules: ["assistant_system"],
    priority: "P0",
    promptKey: "operation.assistant_promo",
    inputHints: [
      "新助教偏服务体验型，还是技术陪练型？",
      "想发朋友圈、助教客户群，还是私聊客户？",
      "要不要强调提前预约，避免客户白跑？",
    ],
  },
  {
    id: "am-customer-chat",
    role: "assistant_manager",
    title: "助教客户私聊邀约",
    description: "分场景私聊话术，自然像聊天不骚扰",
    userIntentTemplate: "助教客户好久没约了，帮我写个自然点的私聊邀约",
    targetCustomerType: "assistant",
    outputPackage: ["private_chat", "execution_tips"],
    sceneTags: ["助教", "私聊", "邀约", "客户维护"],
    requiredProfileModules: ["assistant_system", "customer_structure"],
    priority: "P0",
    promptKey: "operation.assistant_outreach",
    inputHints: [
      "客户多久没来了？一周、半个月还是更久？",
      "想约客户来打球、体验助教服务，还是参加活动？",
      "语气要熟人自然，还是礼貌一点？",
    ],
  },
  {
    id: "am-short-video-copy",
    role: "assistant_manager",
    title: "助教短视频配文",
    description: "标题+配文+话题标签，展示专业形象",
    userIntentTemplate: "助教拍了条短视频，帮我配个文案，展示专业台球技术",
    targetCustomerType: "assistant",
    outputPackage: ["short_video", "moments"],
    sceneTags: ["助教", "短视频", "获客"],
    requiredProfileModules: ["assistant_system", "content_style"],
    priority: "P0",
    promptKey: "operation.short_video",
    inputHints: [
      "视频内容是什么？助教打球、教学、门店氛围还是客户互动？",
      "想要轻松自然，还是更有传播感？",
      "要不要顺带引导预约助教或到店体验？",
    ],
  },
  {
    id: "am-customer-group-maintain",
    role: "assistant_manager",
    title: "助教客户群维护",
    description: "群通知+私聊维护，专业不骚扰",
    userIntentTemplate: "助教客户群发今日助教可约通知，顺便维护一下最近不太活跃的客户",
    targetCustomerType: "assistant",
    outputPackage: ["group_notice", "private_chat", "execution_tips"],
    sceneTags: ["助教客户群", "私域", "维护"],
    requiredProfileModules: ["assistant_system", "private_domain_groups"],
    priority: "P0",
    promptKey: "operation.group_content",
    inputHints: [
      "想发群通知、私聊维护，还是两者都要？",
      "最近不太活跃的客户大概多久没约了？",
      "要不要顺带提今天助教可约或近期活动？",
    ],
  },
  {
    id: "am-pk-plan",
    role: "assistant_manager",
    title: "助教 PK 方案",
    description: "PK规则+指标+追踪表，公平透明",
    userIntentTemplate: "这个月想搞个助教PK，帮我设计一下规则和追踪方式",
    targetCustomerType: "assistant",
    outputPackage: ["pk_plan", "execution_tips"],
    sceneTags: ["助教", "PK", "激励"],
    requiredProfileModules: ["assistant_system"],
    priority: "P1",
    promptKey: "operation.performance_template",
    inputHints: [
      "PK 重点是上钟数、客户好评、预约转化，还是综合指标？",
      "周期是一周、半月还是一个月？",
      "要不要设计追踪表方便每天更新数据？",
    ],
  },
  {
    id: "am-daily-report",
    role: "assistant_manager",
    title: "助教服务日报",
    description: "到岗/上钟/预约数据汇总+明日计划",
    userIntentTemplate: "帮我写今天的助教管理日报，今天助教全部到岗，预约还行",
    targetCustomerType: "assistant",
    outputPackage: ["daily_report", "execution_tips"],
    sceneTags: ["日报", "助教管理", "汇报"],
    requiredProfileModules: ["assistant_system"],
    priority: "P0",
    promptKey: "operation.daily_report",
    inputHints: [
      "今天助教到岗情况？全部到岗、有人请假还是部分到岗？",
      "上钟和预约数据怎么样？比昨天好还是差？",
      "明天需要安排哪些重点？比如助教排班、客户回访。",
    ],
  },
  {
    id: "am-recruitment",
    role: "assistant_manager",
    title: "助教招聘文案",
    description: "合规岗位描述+面试邀约话术",
    userIntentTemplate: "想招几个助教，帮我写招聘文案和面试邀约话术，要合规专业",
    targetCustomerType: "all",
    outputPackage: ["moments", "private_chat", "execution_tips"],
    sceneTags: ["助教", "招聘", "合规"],
    requiredProfileModules: ["assistant_system"],
    priority: "P1",
    promptKey: "recruitment.multi_platform",
    inputHints: [
      "想招几个助教？偏服务体验型还是技术陪练型？",
      "招聘文案发朋友圈、招聘平台，还是私域群？",
      "要不要同时准备面试邀约话术？",
    ],
  },
  {
    id: "am-moments-promo",
    role: "assistant_manager",
    title: "助教朋友圈推广",
    description: "助教到店/可约的朋友圈推广文案",
    userIntentTemplate: "帮我写一条助教朋友圈推广文案，让客户知道今天助教可以约",
    targetCustomerType: "assistant",
    outputPackage: ["moments", "execution_tips"],
    sceneTags: ["助教", "朋友圈", "推广"],
    requiredProfileModules: ["assistant_system"],
    priority: "P0",
    promptKey: "operation.assistant_promo",
    inputHints: [
      "是今日助教可约，还是新助教到店？",
      "助教偏服务体验型，还是技术陪练型？",
      "要不要强调提前预约，避免客户白跑？",
    ],
  },
  {
    id: "am-performance-review",
    role: "assistant_manager",
    title: "助教业绩复盘",
    description: "月度/周度助教上钟数据分析话术",
    userIntentTemplate: "帮我写一份助教业绩复盘，分析最近助教上钟数据和客户反馈",
    targetCustomerType: "assistant",
    outputPackage: ["daily_report", "execution_tips"],
    sceneTags: ["助教", "业绩", "复盘"],
    requiredProfileModules: ["assistant_system"],
    priority: "P1",
    promptKey: "operation.performance_template",
    inputHints: [
      "复盘周期是周度还是月度？",
      "重点分析上钟数、客户好评、预约转化，还是综合表现？",
      "要不要输出改进建议和下阶段目标？",
    ],
  },
  {
    id: "am-assistant-booking",
    role: "assistant_manager",
    title: "助教预约转化",
    description: "预约跟进+回访+课时推荐话术",
    userIntentTemplate: "客户问了助教价格没下文，帮我写跟进话术",
    targetCustomerType: "assistant",
    outputPackage: ["private_chat", "execution_tips"],
    sceneTags: ["助教", "预约", "转化"],
    requiredProfileModules: ["assistant_system"],
    priority: "P1",
    promptKey: "operation.assistant_booking",
    inputHints: [
      "客户是第一次问还是之前体验过？",
      "客户犹豫的原因？价格、时间还是不了解服务？",
      "要不要写预约提醒和体验后回访话术？",
    ],
  },
  {
    id: "am-member-assistant-notice",
    role: "assistant_manager",
    title: "会员群助教可约",
    description: "会员群专属助教可约通知，有人情味",
    userIntentTemplate: "会员群发个助教今天可约的通知，语气要有会员专属感",
    targetCustomerType: "old",
    outputPackage: ["group_notice", "execution_tips"],
    sceneTags: ["会员群", "助教", "可约"],
    requiredProfileModules: ["assistant_system", "private_domain_groups"],
    priority: "P1",
    promptKey: "operation.member_assistant_notice",
    inputHints: [
      "今天哪些助教可约？",
      "会员群语气要不同于助教客户群，更有人情味。",
      "不要把助教写成会员免费权益。",
    ],
  },
  {
    id: "am-7day-screening",
    role: "assistant_manager",
    title: "新人7天培训计划",
    description: "新助教入职7天筛选制SOP，含每日任务、考核标准、带教方法",
    userIntentTemplate: "新来了几个助教，帮我制定一个7天培训筛选计划",
    targetCustomerType: "all",
    outputPackage: ["sop_checklist", "execution_tips"],
    sceneTags: ["助教", "培训", "筛选", "新人"],
    requiredProfileModules: ["assistant_system"],
    priority: "P1",
    promptKey: "operation.assistant_7day_screening",
    inputHints: [
      "新助教有几个人？什么类型（服务体验/技术陪练）？",
      "目前有助教管理带教吗？",
    ],
  },
  {
    id: "am-assistant-supervision",
    role: "assistant_manager",
    title: "助教督导与目标管理",
    description: "给助教定日/月目标、督导主动获客（不主动怎么处理）、带教与维客，按行业标准来",
    userIntentTemplate: "帮我做一套助教团队的督导和目标管理办法",
    targetCustomerType: "all",
    outputPackage: ["sop_checklist", "execution_tips"],
    sceneTags: ["助教", "督导", "目标", "管理", "带教", "获客", "维客"],
    requiredProfileModules: ["assistant_system"],
    priority: "P1",
    promptKey: "operation.assistant_supervision",
    inputHints: [
      "手下几个助教？想解决什么（定目标 / 有人不主动获客 / 带教 / 维客）？",
      "有没有具体某个助教的情况要处理？",
    ],
  },
  {
    id: "am-assistant-difficult",
    role: "assistant_manager",
    title: "助教疑难场景应对",
    description: "客户对助教有想法 / 红包 / 越界等棘手场景，守边界又不伤客情的话术",
    userIntentTemplate: "有客户对助教有想法，帮我想想怎么专业化解、守住边界又不得罪人",
    targetCustomerType: "all",
    outputPackage: ["private_chat", "execution_tips"],
    sceneTags: ["助教", "疑难", "越界", "红包", "边界", "话术"],
    requiredProfileModules: ["assistant_system"],
    priority: "P1",
    promptKey: "operation.assistant_difficult",
    inputHints: [
      "具体什么情况？（客户有想法 / 给红包 / 越界 / 难伺候）",
      "想要应对话术，还是处理原则？",
    ],
  },
];

/* ─── 前厅 frontdesk — 15 张卡片 ─── */

const FRONTDESK_TASKS: RoleTaskCard[] = [
  {
    id: "fd-groupbuy-add-wechat",
    role: "frontdesk",
    title: "团购核销后加微信",
    description: "自然话术引导团购客加微信，不给压力",
    userIntentTemplate: "团购客户来了，核销后怎么加微信比较自然，帮我写个话术",
    targetCustomerType: "groupbuy",
    outputPackage: ["private_chat", "sop_checklist", "execution_tips"],
    sceneTags: ["团购", "加微信", "前厅", "转化"],
    requiredProfileModules: ["commerce_rules"],
    priority: "P0",
    promptKey: "operation.groupbuy_to_private",
    inputHints: [
      "客户刚到店、刚核销，还是已经打完球？",
      "想要自然加微信话术，还是顺便引导进群？",
      "不要强推一卡通充值，可以写清楚。",
    ],
  },
  {
    id: "fd-new-customer-reception",
    role: "frontdesk",
    title: "新客接待",
    description: "第一次到店标准化接待流程和话术",
    userIntentTemplate: "第一次来的客户，前台怎么说比较自然，帮我写一套接待话术",
    targetCustomerType: "new",
    outputPackage: ["private_chat", "sop_checklist", "execution_tips"],
    sceneTags: ["前厅", "新客", "接待", "SOP"],
    requiredProfileModules: ["content_style"],
    priority: "P0",
    promptKey: "operation.frontdesk_sop",
    inputHints: [
      "客户是团购来的，自己走进来的，还是朋友带来的？",
      "想生成接待话术、引导介绍，还是引导加微信进群？",
      "要不要顺带介绍一下门店桌型、助教或会员？",
    ],
  },
  {
    id: "fd-member-inquiry",
    role: "frontdesk",
    title: "客户问会员怎么回",
    description: "自然引导客户了解，转给店长处理",
    userIntentTemplate: "有客人问会员怎么弄，我不确定价格，怎么回比较自然",
    targetCustomerType: "groupbuy",
    outputPackage: ["private_chat", "execution_tips"],
    sceneTags: ["前厅", "会员", "话术"],
    requiredProfileModules: ["commerce_rules"],
    priority: "P0",
    promptKey: "operation.frontdesk_sop",
    inputHints: [
      "客户是散客问会员，还是团购客想了解会员？",
      "想要简短回复，还是详细引导介绍会员？",
      "不确定价格时，是否提醒转给店长处理？",
    ],
  },
  {
    id: "fd-assistant-inquiry",
    role: "frontdesk",
    title: "客户问助教怎么回",
    description: "自然引导了解助教服务，表达得体",
    userIntentTemplate: "有客人问助教怎么约、多少钱，我怎么说比较自然",
    targetCustomerType: "new",
    outputPackage: ["private_chat", "execution_tips"],
    sceneTags: ["前厅", "助教", "话术"],
    requiredProfileModules: ["assistant_system"],
    priority: "P0",
    promptKey: "operation.frontdesk_sop",
    inputHints: [
      "客户是第一次问助教，还是已经有意向预约？",
      "想要简短回复，还是详细介绍助教服务？",
      "要不要提醒到店后帮他看时间和合适助教？",
    ],
  },
  {
    id: "fd-matchmaking-inquiry",
    role: "frontdesk",
    title: "客户问有没有人一起打",
    description: "撮合搭子、引导进群的自然话术",
    userIntentTemplate: "有个客户一个人来的，问有没有人一起打，怎么回能撮合一下",
    targetCustomerType: "new",
    outputPackage: ["private_chat", "group_notice", "execution_tips"],
    sceneTags: ["前厅", "搭子", "撮合", "进群"],
    requiredProfileModules: ["private_domain_groups"],
    priority: "P0",
    promptKey: "operation.partner_match",
    inputHints: [
      "客户是新手想找人打，还是有一定水平想找搭子？",
      "想引导进搭子群、竞技群，还是直接在店里撮合？",
      "要不要顺带介绍门店的约局活动或周赛？",
    ],
  },
  {
    id: "fd-complaint-handling",
    role: "frontdesk",
    title: "投诉安抚",
    description: "排队/服务不满时的安抚话术，专业处理",
    userIntentTemplate: "客人排队太久不高兴了，帮我写个安抚的话术，不要说送东西什么的",
    targetCustomerType: "new",
    outputPackage: ["private_chat", "execution_tips"],
    sceneTags: ["前厅", "投诉", "安抚"],
    requiredProfileModules: [],
    priority: "P0",
    promptKey: "operation.complaint_handling",
    inputHints: [
      "客户是因为排队、服务、环境还是其他原因不满？",
      "想要安抚话术，还是后续跟进建议？",
      "是否明确不主动提补偿、折扣或送东西？",
    ],
  },
  {
    id: "fd-opening-checklist",
    role: "frontdesk",
    title: "开店检查表",
    description: "逐条可勾选的开店检查清单，不漏东西",
    userIntentTemplate: "早班开店总是漏东西，帮我做个逐条的开店检查表",
    targetCustomerType: "all",
    outputPackage: ["sop_checklist", "execution_tips"],
    sceneTags: ["前厅", "开店", "SOP", "检查"],
    requiredProfileModules: [],
    priority: "P1",
    promptKey: "operation.opening_closing_sop",
    inputHints: [
      "是开店检查、闭店检查，还是卫生检查？",
      "要不要按前厅、球桌、卫生、设备分组？",
      "需要适合员工群发布，还是内部执行清单？",
    ],
  },
  {
    id: "fd-closing-checklist",
    role: "frontdesk",
    title: "闭店检查表",
    description: "逐条可勾选的闭店检查清单，不漏东西",
    userIntentTemplate: "晚班闭店容易漏关灯关设备，帮我做个逐条的闭店检查表",
    targetCustomerType: "all",
    outputPackage: ["sop_checklist", "execution_tips"],
    sceneTags: ["前厅", "闭店", "SOP", "检查"],
    requiredProfileModules: [],
    priority: "P1",
    promptKey: "operation.opening_closing_sop",
  },
  {
    id: "fd-price-inquiry",
    role: "frontdesk",
    title: "客户问价格",
    description: "前台应对价格咨询的话术和应答",
    userIntentTemplate: "有客人问打球多少钱，帮我写一套前台应对价格咨询的话术",
    targetCustomerType: "new",
    outputPackage: ["private_chat", "execution_tips"],
    sceneTags: ["前厅", "价格", "话术"],
    requiredProfileModules: ["commerce_rules"],
    priority: "P0",
    promptKey: "operation.frontdesk_sop",
    inputHints: [
      "客户是散客、团购客，还是问会员价？",
      "想要简短报价，还是引导了解会员或助教服务？",
      "有没有不想主动提的价格或优惠？",
    ],
  },
  {
    id: "fd-equipment-inquiry",
    role: "frontdesk",
    title: "客户问桌型设备",
    description: "前台介绍桌型和设备的话术",
    userIntentTemplate: "有客人问店里有什么台球桌，帮我写一套介绍桌型和设备的话术",
    targetCustomerType: "new",
    outputPackage: ["private_chat", "execution_tips"],
    sceneTags: ["前厅", "桌型", "设备", "话术"],
    requiredProfileModules: ["equipment"],
    priority: "P0",
    promptKey: "operation.frontdesk_sop",
    inputHints: [
      "客户问的是乔氏、斯诺克，还是普通台球桌？",
      "想要简短介绍，还是详细介绍各桌型特点？",
      "要不要顺带引导客户到店体验或预约指定桌型？",
    ],
  },
  {
    id: "fd-cart-promotion",
    role: "frontdesk",
    title: "小推车促销话术",
    description: "饮料/零食/烟/果盘的服务式推销话术",
    userIntentTemplate: "帮我写几套推车促销话术，自然一点，不要像推销",
    targetCustomerType: "all",
    outputPackage: ["private_chat", "sop_checklist", "execution_tips"],
    sceneTags: ["前厅", "推车", "促销", "话术"],
    requiredProfileModules: [],
    priority: "P0",
    promptKey: "operation.cart_promotion",
    inputHints: [
      "想写哪几类？饮料、零食、烟、果盘，还是全套？",
      "下午场还是晚场？话术风格不一样。",
      "要不要带促销记录表模板？",
    ],
  },
  {
    id: "fd-empty-table-promo",
    role: "frontdesk",
    title: "空台促活",
    description: "空台时朋友圈+群公告促活内容",
    userIntentTemplate: "下午空台很多，帮我写促活内容发朋友圈和群",
    targetCustomerType: "all",
    outputPackage: ["moments", "group_notice", "execution_tips"],
    sceneTags: ["前厅", "空台", "促活"],
    requiredProfileModules: [],
    priority: "P1",
    promptKey: "operation.empty_table_promo",
    inputHints: [
      "哪个时间段空台？下午、晚上还是全天？",
      "想发朋友圈、群公告，还是两者都要？",
      "要不要引导约球或搭子局？",
    ],
  },
  {
    id: "fd-departure-followup",
    role: "frontdesk",
    title: "离店跟进",
    description: "客户离店后的自然回访话术",
    userIntentTemplate: "客户走后怎么跟进比较好，帮我写个自然点的回访话术",
    targetCustomerType: "new",
    outputPackage: ["private_chat", "execution_tips"],
    sceneTags: ["前厅", "跟进", "回访"],
    requiredProfileModules: [],
    priority: "P1",
    promptKey: "operation.departure_followup",
    inputHints: [
      "客户是新客、老客还是团购客？不同类型跟进方式不一样。",
      "想写微信私聊跟进，还是朋友圈引导？",
      "不要骚扰感，2-3小时后再发。",
    ],
  },
  {
    id: "fd-customer-group-guide",
    role: "frontdesk",
    title: "引导客户进群",
    description: "按客户类型引导进对应群的话术",
    userIntentTemplate: "不同客户该进哪个群，帮我写引导话术",
    targetCustomerType: "new",
    outputPackage: ["private_chat", "execution_tips"],
    sceneTags: ["前厅", "进群", "私域"],
    requiredProfileModules: ["private_domain_groups"],
    priority: "P1",
    promptKey: "operation.customer_group_guide",
    inputHints: [
      "客户是团购客、会员、竞技客户还是散客？",
      "门店有哪些群？客户群、会员群、竞技群？",
      "不要强制拉群，不要承诺未落地的权益。",
    ],
  },
  {
    id: "fd-opening-closing-sop",
    role: "frontdesk",
    title: "开店闭店SOP",
    description: "逐条可勾选的开店+闭店检查清单",
    userIntentTemplate: "帮我做一套开店和闭店的SOP检查清单，每条可勾选",
    targetCustomerType: "all",
    outputPackage: ["sop_checklist", "execution_tips"],
    sceneTags: ["前厅", "SOP", "开店", "闭店"],
    requiredProfileModules: [],
    priority: "P1",
    promptKey: "operation.opening_closing_sop",
    inputHints: [
      "想分开店和闭店两套清单，还是合在一起？",
      "检查表控制在15条以内，够用吗？",
      "要不要按区域分组？前台、球桌、卫生、设备。",
    ],
  },
  {
    id: "fd-equipment-management",
    role: "frontdesk",
    title: "电器管理报备",
    description: "空调/灯光报备表模板+开关策略",
    userIntentTemplate: "帮我做一个电器管理报备表，每小时记录空调开启情况",
    targetCustomerType: "all",
    outputPackage: ["sop_checklist", "execution_tips"],
    sceneTags: ["前厅", "电器", "节能"],
    requiredProfileModules: [],
    priority: "P2",
    promptKey: "operation.equipment_management",
    inputHints: [
      "门店空调几台？大厅和包厢分开记录？",
      "想写报备表模板还是开关策略建议？",
      "节能但不要影响客户舒适度。",
    ],
  },
  {
    id: "fd-hygiene-check",
    role: "frontdesk",
    title: "卫生检查清单",
    description: "逐条可勾选的卫生检查清单+记录模板",
    userIntentTemplate: "帮我做一个卫生检查清单，涵盖台面、地面、洗手间、休息区和吧台",
    targetCustomerType: "all",
    outputPackage: ["sop_checklist", "execution_tips"],
    sceneTags: ["前厅", "卫生", "检查"],
    requiredProfileModules: [],
    priority: "P2",
    promptKey: "operation.hygiene_check",
    inputHints: [
      "想分区域检查还是整体清单？",
      "检查表控制在15条以内。",
      "要不要带不合格整改追踪？",
    ],
  },
];

/* ─── 老板 boss — 8 张卡片 ─── */

const BOSS_TASKS: RoleTaskCard[] = [
  {
    id: "boss-daily-brief",
    role: "boss",
    title: "今日经营简报",
    description: "关键指标一览+异常提醒+运营建议",
    userIntentTemplate: "帮我整理一份今天球房经营简报，重点看人气、客户、助教、会员群和明天要安排的事。",
    targetCustomerType: "all",
    outputPackage: ["daily_report", "execution_tips"],
    sceneTags: ["老板", "简报", "经营"],
    requiredProfileModules: ["business_goals", "customer_structure"],
    priority: "P0",
    promptKey: "operation.daily_task_list",
    inputHints: [
      "今天想重点看哪些内容？人气、营收、助教、会员群还是竞技群？",
      "是发给自己看，还是发到管理群？",
      "明天最重要的动作是什么？老客回访、助教预约还是活动报名？",
    ],
  },
  {
    id: "boss-weekly-focus",
    role: "boss",
    title: "本周重点安排",
    description: "本周运营方向和重点工作部署",
    userIntentTemplate: "帮我整理本周球房重点工作安排，适合发给店长和管理层执行。",
    targetCustomerType: "all",
    outputPackage: ["daily_report", "execution_tips"],
    sceneTags: ["老板", "管理", "周计划"],
    requiredProfileModules: ["business_goals"],
    priority: "P0",
    promptKey: "operation.daily_task_list",
    inputHints: [
      "本周最想提升什么？老客回流、助教预约、周赛人气还是团购转化？",
      "要不要分老板、店长、前厅、助教管理几类任务？",
      "是否需要写成管理层能直接执行的清单？",
    ],
  },
  {
    id: "boss-staff-group-notice",
    role: "boss",
    title: "员工群管理通知",
    description: "管理层下达通知，正式但不官方",
    userIntentTemplate: "帮我写一条发员工群的管理通知，语气要清楚，但不要太凶。",
    targetCustomerType: "all",
    outputPackage: ["group_notice", "sop_checklist"],
    sceneTags: ["老板", "管理", "员工群"],
    requiredProfileModules: ["private_domain_groups"],
    priority: "P0",
    promptKey: "operation.group_content",
    inputHints: [
      "这条通知是关于卫生、服务、排班、接待，还是活动执行？",
      "要不要明确负责人和完成时间？",
      "语气要温和提醒，还是正式一点？",
    ],
  },
  {
    id: "boss-assistant-review",
    role: "boss",
    title: "助教业务复盘",
    description: "助教团队月度表现分析和提升建议",
    userIntentTemplate: "帮我整理一份助教业务复盘，看看最近助教预约、客户维护和上钟转化可以怎么提升。",
    targetCustomerType: "assistant",
    outputPackage: ["daily_report", "execution_tips"],
    sceneTags: ["老板", "助教", "复盘"],
    requiredProfileModules: ["assistant_system"],
    priority: "P0",
    promptKey: "operation.performance_template",
    inputHints: [
      "最近想复盘助教预约、服务体验、短视频获客，还是助教客户维护？",
      "有没有具体问题？比如到店少、转化弱、内容少、客户复约少。",
      "要不要输出成管理层执行建议？",
    ],
  },
  {
    id: "boss-old-customer-recall",
    role: "boss",
    title: "老客户回流安排",
    description: "老客户回流的系统化方案，自然不营销",
    userIntentTemplate: "帮我设计一套老客户回流安排，包含朋友圈、私聊和群里提醒，不要太营销。",
    targetCustomerType: "old",
    outputPackage: ["execution_tips", "private_chat", "moments"],
    sceneTags: ["老板", "老客户", "回流"],
    requiredProfileModules: ["customer_structure", "content_style"],
    priority: "P1",
    promptKey: "operation.old_customer_recall",
    inputHints: [
      "老客户大概多久没来了？",
      "这次想用朋友圈、私聊，还是会员群一起做？",
      "今天有什么可说的？空台、助教、周赛还是氛围？",
    ],
  },
  {
    id: "boss-profile-completeness-check",
    role: "boss",
    title: "门店资料完整度检查",
    description: "检查画像完善程度，补充缺失信息",
    userIntentTemplate: "帮我检查一下门店资料还应该补哪些信息，方便 AI 后面生成内容更贴近本店。",
    targetCustomerType: "all",
    outputPackage: ["sop_checklist", "execution_tips"],
    sceneTags: ["老板", "资料", "画像"],
    requiredProfileModules: [],
    priority: "P0",
    promptKey: "operation.diagnosis_tool",
    inputHints: [
      "想优先补哪个模块？助教体系、会员群、竞技群、桌型设备还是内容风格？",
      "是给自己看，还是安排店长去补？",
      "要不要输出成一个补资料清单？",
    ],
  },
  {
    id: "boss-monthly-report",
    role: "boss",
    title: "月度运营汇报",
    description: "数据趋势+对比分析+问题+下月计划",
    userIntentTemplate: "帮我整理一份月度运营汇报，重点看趋势和问题",
    targetCustomerType: "all",
    outputPackage: ["daily_report", "execution_tips"],
    sceneTags: ["老板", "月报", "汇报"],
    requiredProfileModules: ["business_goals"],
    priority: "P1",
    promptKey: "operation.monthly_report",
    inputHints: [
      "这个月最值得关注的数据是什么？",
      "重点关注趋势和同比，不是罗列数字。",
      "下个月最想提升什么？",
    ],
  },
  {
    id: "boss-activity-direction",
    role: "boss",
    title: "活动方向建议",
    description: "基于季节/节假日/门店数据给出活动方向",
    userIntentTemplate: "下个月搞什么活动好，帮我给几个方向建议",
    targetCustomerType: "all",
    outputPackage: ["activity_plan", "execution_tips"],
    sceneTags: ["老板", "活动", "方向"],
    requiredProfileModules: ["business_goals", "events"],
    priority: "P2",
    promptKey: "operation.activity_direction",
    inputHints: [
      "现在是淡季还是旺季？有什么节假日？",
      "重点是拉人气、卖会员、还是做赛事？",
      "建议是参考，老板自己拍板。",
    ],
  },
  {
    id: "boss-manager-pk",
    role: "boss",
    title: "管理层PK方案",
    description: "设计店长/前厅/助教管理之间的业绩PK机制",
    userIntentTemplate: "帮我设计一个管理层之间的PK方案，激发团队竞争意识",
    targetCustomerType: "all",
    outputPackage: ["pk_plan", "execution_tips"],
    sceneTags: ["PK", "管理层", "激励"],
    requiredProfileModules: [],
    priority: "P1",
    promptKey: "operation.manager_pk_plan",
    inputHints: [
      "目前有哪些管理岗位？各几个人？",
      "想PK哪些指标？台费、好评、助教业绩？",
    ],
  },
  {
    id: "boss-investment-return",
    role: "boss",
    title: "投资回报经营表",
    description: "制作投资回报周期分析，含成本、收入、盈亏平衡、回报周期",
    userIntentTemplate: "帮我做一个投资回报周期经营表，看看什么时候能回本",
    targetCustomerType: "all",
    outputPackage: ["daily_report", "execution_tips"],
    sceneTags: ["投资", "回报", "经营分析"],
    requiredProfileModules: ["basic"],
    priority: "P1",
    promptKey: "operation.investment_return",
    inputHints: [
      "总投资额大概多少？",
      "目前月均营业额多少？",
    ],
  },
  {
    id: "boss-promotion-analysis",
    role: "boss",
    title: "活动效果复盘",
    description: "对比活动前后的数据变化，分析是否达成目标",
    userIntentTemplate: "帮我复盘一下上次活动的效果，对比活动前后的数据",
    targetCustomerType: "all",
    outputPackage: ["daily_report", "execution_tips"],
    sceneTags: ["复盘", "活动", "数据分析"],
    requiredProfileModules: [],
    priority: "P1",
    promptKey: "operation.promotion_analysis",
    inputHints: [
      "活动名称和时间？",
      "活动前日均营业额大概多少？活动期间呢？",
      "目标达成了吗？",
    ],
  },
];

/* ─── 运营/内容 operator — 9 张卡片 ─── */

const OPERATOR_TASKS: RoleTaskCard[] = [
  {
    id: "op-weekly-content-plan",
    role: "operator",
    title: "本周内容规划",
    description: "规划朋友圈/短视频/群内容多渠道排期",
    userIntentTemplate: "帮我做一份本周球房内容规划，包含朋友圈、会员群、竞技群和助教内容。",
    targetCustomerType: "all",
    outputPackage: ["activity_plan", "execution_tips"],
    sceneTags: ["运营", "内容", "规划"],
    requiredProfileModules: ["content_style", "business_goals"],
    priority: "P0",
    promptKey: "operation.group_content",
    inputHints: [
      "本周重点是拉新、老客回流、助教预约，还是周赛人气？",
      "需要规划几天内容？3 天、5 天还是 7 天？",
      "要不要分朋友圈、群公告、短视频配文几个渠道？",
    ],
  },
  {
    id: "op-moments-plan",
    role: "operator",
    title: "朋友圈发布计划",
    description: "安排本周朋友圈发布节奏和内容方向",
    userIntentTemplate: "帮我安排几条这周可以发的朋友圈内容，语气自然一点，不要像广告。",
    targetCustomerType: "all",
    outputPackage: ["moments", "execution_tips"],
    sceneTags: ["运营", "朋友圈", "计划"],
    requiredProfileModules: ["content_style"],
    priority: "P0",
    promptKey: "copywriting.moments",
    inputHints: [
      "想发几条？3 条、5 条还是每天一条？",
      "要不要覆盖空台、助教、周赛、老客、门店氛围？",
      "有没有不想写的内容？比如不写优惠、不写价格。",
    ],
  },
  {
    id: "op-short-video-copy",
    role: "operator",
    title: "短视频配文",
    description: "球房短视频的标题+配文+话题标签",
    userIntentTemplate: "帮我给一条球房短视频写配文，适合发朋友圈或短视频平台。",
    targetCustomerType: "all",
    outputPackage: ["short_video", "moments"],
    sceneTags: ["运营", "短视频", "内容"],
    requiredProfileModules: ["content_style"],
    priority: "P0",
    promptKey: "operation.short_video",
    inputHints: [
      "视频内容是什么？助教、门店氛围、客人打球、周赛还是台球桌？",
      "想要轻松自然，还是更有传播感？",
      "要不要顺带引导到店、预约助教或参加活动？",
    ],
  },
  {
    id: "op-member-group-content",
    role: "operator",
    title: "会员群内容维护",
    description: "会员群日常内容，有人情味不广告",
    userIntentTemplate: "帮我给会员群设计几条日常维护内容，不要一直发广告。",
    targetCustomerType: "old",
    outputPackage: ["group_notice", "execution_tips"],
    sceneTags: ["运营", "会员群", "私域"],
    requiredProfileModules: ["private_domain_groups", "commerce_rules"],
    priority: "P0",
    promptKey: "operation.group_content",
    inputHints: [
      "想做空台提醒、活动提醒、老客关怀，还是助教可约通知？",
      "语气要熟人自然，还是简短通知？",
      "是否明确不写会员优惠和充值权益？",
    ],
  },
  {
    id: "op-competition-group-content",
    role: "operator",
    title: "竞技群内容维护",
    description: "竞技群约局/赛事/练球内容节奏",
    userIntentTemplate: "帮我给竞技群设计几条内容，活跃一下约局、周赛和练球氛围。",
    targetCustomerType: "competition",
    outputPackage: ["group_notice", "execution_tips"],
    sceneTags: ["运营", "竞技群", "私域"],
    requiredProfileModules: ["private_domain_groups", "events"],
    priority: "P1",
    promptKey: "operation.group_content",
    inputHints: [
      "想发约球、周赛报名、练球局，还是赛后战报？",
      "时间是今晚、周末还是本周？",
      "要不要提乔氏、斯诺克或普通台球桌？",
    ],
  },
  {
    id: "op-festival-poster-copy",
    role: "operator",
    title: "活动海报文案",
    description: "节日/活动海报的多渠道文案",
    userIntentTemplate: "帮我写一套球房活动海报文案，适合朋友圈和群里同步发。",
    targetCustomerType: "all",
    outputPackage: ["poster_copy", "moments", "group_notice"],
    sceneTags: ["运营", "海报", "活动"],
    requiredProfileModules: ["events", "content_style"],
    priority: "P0",
    promptKey: "operation.poster_copy",
    inputHints: [
      "是什么活动？节日、周赛、会员活动、助教活动还是团建？",
      "有没有明确优惠或价格？没有就不要编。",
      "要不要同时给朋友圈文案和群公告？",
    ],
  },
  {
    id: "op-assistant-content",
    role: "operator",
    title: "助教素材文案",
    description: "为助教推广准备的文案素材",
    userIntentTemplate: "帮我准备一些助教推广的文案素材，适合朋友圈和助教客户群",
    targetCustomerType: "assistant",
    outputPackage: ["moments", "group_notice", "execution_tips"],
    sceneTags: ["运营", "助教", "素材"],
    requiredProfileModules: ["assistant_system", "content_style"],
    priority: "P0",
    promptKey: "operation.assistant_promo",
    inputHints: [
      "素材重点是助教服务体验、技术陪练，还是新助教到店？",
      "要发朋友圈、助教客户群，还是私聊客户？",
      "要不要强调提前预约，避免客户白跑？",
    ],
  },
  {
    id: "op-store-atmosphere",
    role: "operator",
    title: "门店氛围内容",
    description: "门店氛围营造的朋友圈/群内容",
    userIntentTemplate: "帮我写一些展示门店氛围的内容，适合朋友圈和会员群",
    targetCustomerType: "all",
    outputPackage: ["moments", "group_notice", "execution_tips"],
    sceneTags: ["运营", "氛围", "门店"],
    requiredProfileModules: ["content_style"],
    priority: "P0",
    promptKey: "operation.store_atmosphere",
    inputHints: [
      "想展示什么氛围？热闹、专业、舒适还是社交？",
      "要发朋友圈、会员群，还是竞技群？",
      "有没有不想写的内容？比如不写优惠、不写价格。",
    ],
  },
  {
    id: "op-event-promotion",
    role: "operator",
    title: "活动预热与复盘",
    description: "活动前的预热推广和活动后的总结复盘内容",
    userIntentTemplate: "帮我写一套活动预热和复盘内容，活动前预热推广，活动后总结",
    targetCustomerType: "all",
    outputPackage: ["moments", "group_notice", "daily_report", "execution_tips"],
    sceneTags: ["运营", "活动", "预热", "复盘"],
    requiredProfileModules: ["events", "content_style"],
    priority: "P0",
    promptKey: "operation.tournament",
    inputHints: [
      "是什么活动？周赛、节日活动、会员活动还是助教活动？",
      "需要预热文案、复盘总结，还是两者都要？",
      "活动有没有具体数据？参与人数、氛围、精彩瞬间？",
    ],
  },
  {
    id: "op-douyin-matrix",
    role: "operator",
    title: "抖音矩阵运营方案",
    description: "制定主号+助教号+教练号的矩阵内容策略和发布节奏",
    userIntentTemplate: "帮我制定一个抖音矩阵账号运营方案，我们想全员做抖音",
    targetCustomerType: "all",
    outputPackage: ["execution_tips", "sop_checklist"],
    sceneTags: ["抖音", "矩阵", "短视频", "直播"],
    requiredProfileModules: ["assistant_system"],
    priority: "P1",
    promptKey: "operation.douyin_matrix_plan",
    inputHints: [
      "有助教吗？有几个？",
      "有教练吗？几个？",
      "目前有在做抖音吗？粉丝多少？",
    ],
  },
];

/* ─── 教练/赛事 coach — 16 张卡片 ─── */

const COACH_TASKS: RoleTaskCard[] = [
  {
    id: "coach-weekly-tournament-notice",
    role: "coach",
    title: "周赛公告",
    description: "本周周赛公告，适合竞技群和朋友圈",
    userIntentTemplate: "帮我写一条本周周赛公告，适合发竞技群和朋友圈。",
    targetCustomerType: "competition",
    outputPackage: ["group_notice", "moments", "execution_tips"],
    sceneTags: ["教练", "周赛", "公告"],
    requiredProfileModules: ["events"],
    priority: "P0",
    promptKey: "operation.tournament",
    inputHints: [
      "周赛是几号几点？",
      "是否有报名方式、名额、赛制或奖品？没有就不要编。",
      "想语气正式一点，还是轻松一点？",
    ],
  },
  {
    id: "coach-competition-signup",
    role: "coach",
    title: "竞技群报名提醒",
    description: "提醒竞技群报名参加周赛或轻竞技活动",
    userIntentTemplate: "帮我写一条竞技群报名提醒，提醒大家参加周赛或轻竞技活动。",
    targetCustomerType: "competition",
    outputPackage: ["group_notice"],
    sceneTags: ["教练", "报名", "竞技群"],
    requiredProfileModules: ["events", "private_domain_groups"],
    priority: "P0",
    promptKey: "operation.tournament_signup",
    inputHints: [
      "报名截止到什么时候？",
      "是周赛、月赛，还是轻竞技活动？",
      "要不要提醒到店时间和联系方式？",
    ],
  },
  {
    id: "coach-pre-match-reminder",
    role: "coach",
    title: "赛前提醒",
    description: "发给已报名参赛球友的赛前通知",
    userIntentTemplate: "帮我写一条赛前提醒，发给已经报名的球友。",
    targetCustomerType: "competition",
    outputPackage: ["group_notice", "execution_tips"],
    sceneTags: ["教练", "赛前", "提醒"],
    requiredProfileModules: ["events"],
    priority: "P0",
    promptKey: "operation.tournament_signup",
    inputHints: [
      "比赛几点开始？建议几点到店？",
      "要提醒签到、热身、赛制，还是注意事项？",
      "语气要正式通知还是轻松提醒？",
    ],
  },
  {
    id: "coach-light-competition",
    role: "coach",
    title: "轻竞技活动通知",
    description: "练球局/友谊局/小型挑战赛通知",
    userIntentTemplate: "帮我设计一个轻竞技活动通知，让普通球友也愿意参加。",
    targetCustomerType: "competition",
    outputPackage: ["activity_plan", "group_notice"],
    sceneTags: ["教练", "轻竞技", "活动"],
    requiredProfileModules: ["events"],
    priority: "P1",
    promptKey: "operation.partner_match",
    inputHints: [
      "活动是练球局、友谊局，还是小型挑战赛？",
      "适合新手、老客，还是竞技客户？",
      "表达为轻松交流，不涉及高风险对局。",
    ],
  },
  {
    id: "coach-joy-billiards-invite",
    role: "coach",
    title: "乔氏台球桌邀约",
    description: "结合门店乔氏球桌的约局内容",
    userIntentTemplate: "帮我写一条乔氏台球桌相关的邀约内容，适合发给竞技客户。",
    targetCustomerType: "competition",
    outputPackage: ["group_notice", "moments"],
    sceneTags: ["教练", "乔氏", "约局"],
    requiredProfileModules: ["equipment"],
    priority: "P0",
    inputHints: [
      "门店画像里是否已填乔氏台球桌？没有就不要强行写。",
      "是发朋友圈，还是竞技群？",
      "想约练球、周赛热身，还是普通约球？",
    ],
  },
  {
    id: "coach-snooker-invite",
    role: "coach",
    title: "斯诺克邀约",
    description: "斯诺克球友约球，仅引用已填桌型",
    userIntentTemplate: "帮我写一条斯诺克邀约内容，适合发给喜欢斯诺克的球友。",
    targetCustomerType: "competition",
    outputPackage: ["group_notice", "moments"],
    sceneTags: ["教练", "斯诺克", "邀约"],
    requiredProfileModules: ["equipment"],
    priority: "P1",
    inputHints: [
      "门店画像里是否已填斯诺克？没有就不要强行写。",
      "是约人来练，还是发门店特色介绍？",
      "语气要专业一点还是轻松一点？",
    ],
  },
  {
    id: "coach-tournament-signup",
    role: "coach",
    title: "赛前报名推广",
    description: "多渠道报名推广文案+倒计时+私聊邀约",
    userIntentTemplate: "这周末做周赛，报名还不够，帮我写一套报名推广文案",
    targetCustomerType: "competition",
    outputPackage: ["moments", "group_notice", "private_chat", "poster_copy", "execution_tips"],
    sceneTags: ["教练", "赛事", "报名", "推广"],
    requiredProfileModules: ["events"],
    priority: "P0",
    promptKey: "operation.tournament_signup",
    inputHints: [
      "周赛还是月赛？几号几点开始？",
      "目前报名几个人？目标多少？",
      "想发朋友圈、群公告、私聊邀约，还是全套？",
    ],
  },
  {
    id: "coach-tournament-report",
    role: "coach",
    title: "赛后战报",
    description: "专业战报+冠军祝贺+下次赛事预告",
    userIntentTemplate: "比赛刚结束，帮我写一份赛后战报发朋友圈和群里",
    targetCustomerType: "competition",
    outputPackage: ["moments", "group_notice", "private_chat", "execution_tips"],
    sceneTags: ["教练", "战报", "赛事"],
    requiredProfileModules: ["events"],
    priority: "P0",
    promptKey: "operation.tournament_report",
    inputHints: [
      "冠军是谁？亚军是谁？有精彩瞬间吗？",
      "要发朋友圈、群公告，还是私聊祝贺冠军？",
      "下次赛事预计什么时候？要不要预告？",
    ],
  },
  {
    id: "coach-qiangyi-battle",
    role: "coach",
    title: "抢一大战",
    description: "轻竞技社交活动：让条件+报名+主持词",
    userIntentTemplate: "帮我组织一个抢一大战活动，从预热到执行全套内容",
    targetCustomerType: "competition",
    outputPackage: ["moments", "group_notice", "private_chat", "activity_plan", "execution_tips"],
    sceneTags: ["教练", "抢一大战", "轻竞技"],
    requiredProfileModules: ["events"],
    priority: "P0",
    promptKey: "operation.qiangyi_battle",
    inputHints: [
      "下午场还是晚场？还是两场都搞？",
      "让条件怎么定？ABCD档各让多少？",
      "报名费和奖金门店有没有定？没定就用占位。",
    ],
  },
  {
    id: "coach-review-guidance",
    role: "coach",
    title: "好评引导",
    description: "引导客户写好评的话术+好评参考文案",
    userIntentTemplate: "帮我写一套好评引导话术，让客户帮忙在抖音和美团写好评",
    targetCustomerType: "all",
    outputPackage: ["private_chat", "moments", "execution_tips"],
    sceneTags: ["教练", "好评", "引导"],
    requiredProfileModules: ["content_style"],
    priority: "P0",
    promptKey: "operation.review_guidance",
    inputHints: [
      "想引导好评的平台？抖音、美团、大众点评？",
      "想写当面引导话术、微信私聊，还是群里说？",
      "需要好评参考文案吗？",
    ],
  },
  {
    id: "coach-coaching-promo",
    role: "coach",
    title: "教学课程推广",
    description: "课程介绍+推广文案+适合人群+预约引导",
    userIntentTemplate: "帮我推广一下教学课程，写一套朋友圈和群公告文案",
    targetCustomerType: "new",
    outputPackage: ["moments", "group_notice", "private_chat", "execution_tips"],
    sceneTags: ["教练", "教学", "推广"],
    requiredProfileModules: ["assistant_system"],
    priority: "P1",
    promptKey: "operation.coaching_promo",
    inputHints: [
      "推广什么课程？入门、进阶还是专项训练？",
      "课程适合什么水平的客户？新手、有一定基础还是竞技客户？",
      "价格和课时门店有没有定？",
    ],
  },
  {
    id: "coach-competition-customer",
    role: "coach",
    title: "竞技客户维护",
    description: "比赛邀约/搭子撮合/技术交流话术",
    userIntentTemplate: "帮我写竞技客户的维护话术，邀约比赛、搭子撮合和技术交流",
    targetCustomerType: "competition",
    outputPackage: ["private_chat", "group_notice", "execution_tips"],
    sceneTags: ["教练", "竞技", "维护"],
    requiredProfileModules: ["private_domain_groups"],
    priority: "P1",
    promptKey: "operation.competition_customer",
    inputHints: [
      "维护目标是什么？邀约参赛、搭子撮合还是日常交流？",
      "客户水平大概什么档次？A/B/C/D？",
      "想发私聊还是群里说？",
    ],
  },
  {
    id: "coach-tournament-rules",
    role: "coach",
    title: "赛制说明",
    description: "清晰的赛制说明文档+让条件规则",
    userIntentTemplate: "帮我写一份赛制说明，让参赛者清楚比赛规则和让条件",
    targetCustomerType: "competition",
    outputPackage: ["group_notice", "execution_tips"],
    sceneTags: ["教练", "赛制", "规则"],
    requiredProfileModules: ["events"],
    priority: "P1",
    promptKey: "operation.tournament_rules",
    inputHints: [
      "什么赛制？淘汰赛、循环赛、双败淘汰？",
      "让条件怎么定？ABCD档各让多少？",
      "发群里还是需要正式版文档？",
    ],
  },
  {
    id: "coach-champion-poster",
    role: "coach",
    title: "冠军海报",
    description: "冠军海报文案+设计方案说明",
    userIntentTemplate: "比赛冠军出来了，帮我写冠军海报文案",
    targetCustomerType: "competition",
    outputPackage: ["poster_copy", "moments", "execution_tips"],
    sceneTags: ["教练", "冠军", "海报"],
    requiredProfileModules: ["events"],
    priority: "P2",
    promptKey: "operation.champion_poster",
    inputHints: [
      "冠军叫什么名字？什么比赛？",
      "有比赛照片吗？可以配图。",
      "想写海报文案+朋友圈配文，还是只写海报文案？",
    ],
  },
  {
    id: "coach-practice-session",
    role: "coach",
    title: "训练局/练球局通知",
    description: "组织练球和训练，轻松口吻",
    userIntentTemplate: "帮我写一条训练局或练球局通知，适合发竞技群。",
    targetCustomerType: "competition",
    outputPackage: ["group_notice", "private_chat"],
    sceneTags: ["教练", "练球", "训练"],
    requiredProfileModules: ["private_domain_groups"],
    priority: "P1",
    promptKey: "operation.partner_match",
    inputHints: [
      "是今晚、下午还是周末？",
      "适合什么水平的球友？新手、进阶、竞技客户？",
      "要不要提醒轻松练球、友好交流？",
    ],
  },
  {
    id: "coach-groupbuy-to-competition",
    role: "coach",
    title: "团购客转竞技客户",
    description: "引导团购客户体验竞技活动，从散客变成常客",
    userIntentTemplate: "今天有几个团购来的客户，帮我写引导话术，让他们下次还想来打球，最好能参加我们的活动",
    targetCustomerType: "groupbuy",
    outputPackage: ["private_chat", "group_notice", "execution_tips"],
    sceneTags: ["教练", "团购客", "转化", "竞技"],
    requiredProfileModules: ["commerce_rules", "private_domain_groups"],
    priority: "P0",
    promptKey: "operation.competition_customer",
    inputHints: [
      "团购客户是第一次来还是来过几次？",
      "客户水平大概什么样？新手、有点基础、还是打得不错？",
      "想引导进竞技群、参加轻竞技，还是先约下次来打？",
    ],
  },
  {
    id: "coach-newcomer-guide",
    role: "coach",
    title: "新手引导入门",
    description: "降低新手参与门槛，引导从散客变为竞技常客",
    userIntentTemplate: "有个新手客户想学球但怕水平不够，帮我写引导话术，让他觉得来打球没压力",
    targetCustomerType: "new",
    outputPackage: ["private_chat", "execution_tips"],
    sceneTags: ["教练", "新手", "入门", "引导"],
    requiredProfileModules: ["private_domain_groups"],
    priority: "P0",
    promptKey: "operation.competition_customer",
    inputHints: [
      "客户是完全不会打，还是有一定基础？",
      "想引导客户加群、约球、还是了解教练课程？",
      "门店有没有针对新手的活动或体验课？",
    ],
  },
  {
    id: "coach-entertain-casual",
    role: "coach",
    title: "散客接待话术",
    description: "散客到店接待、小游戏推荐、基础教学、组局邀约的全流程话术",
    userIntentTemplate: "帮我写一套散客接待话术，从进店到加微信的全流程",
    targetCustomerType: "new",
    outputPackage: ["private_chat", "execution_tips"],
    sceneTags: ["教练", "散客", "接待", "话术"],
    requiredProfileModules: [],
    priority: "P1",
    promptKey: "operation.coach_entertain_casual",
    inputHints: [
      "客户是自己来的还是朋友带来的？",
      "客户会打球吗？什么水平？",
      "门店有什么桌型？",
    ],
  },
  {
    id: "coach-game-recommend",
    role: "coach",
    title: "小游戏推荐",
    description: "根据客户人数和水平推荐合适的台球小游戏",
    userIntentTemplate: "有几个散客在打球，帮我推荐几个小游戏让他们玩得开心",
    targetCustomerType: "new",
    outputPackage: ["execution_tips"],
    sceneTags: ["教练", "小游戏", "娱乐", "散客"],
    requiredProfileModules: [],
    priority: "P1",
    promptKey: "operation.game_recommend",
    inputHints: [
      "几个客户在打？",
      "大概什么水平？新手还是有一定基础？",
      "预计打多长时间？",
    ],
  },
];

/* ─── 岗位任务映射 ─── */

export const ROLE_TASKS: Record<WorkbenchRole, RoleTaskCard[]> = {
  manager: MANAGER_TASKS,
  assistant_manager: ASSISTANT_MANAGER_TASKS,
  frontdesk: FRONTDESK_TASKS,
  coach: COACH_TASKS,
  operator: OPERATOR_TASKS,
  boss: BOSS_TASKS,
};

/* ─── 按 taskId 查找任务卡片 ─── */

export function getTaskById(taskId: string): RoleTaskCard | undefined {
  for (const tasks of Object.values(ROLE_TASKS)) {
    const found = tasks.find((t) => t.id === taskId);
    if (found) return found;
  }
  return undefined;
}

/* ─── 岗位标签 ─── */

export const ROLE_LABELS: Record<WorkbenchRole, string> = {
  boss: "老板",
  manager: "店长",
  assistant_manager: "助教管理",
  coach: "教练",
  frontdesk: "前厅",
  operator: "运营",
};

export const ROLE_DESCRIPTIONS: Record<WorkbenchRole, string> = {
  boss: "关注全店经营状况和趋势",
  manager: "负责全店日常运营管理",
  assistant_manager: "负责助教团队管理和推广",
  coach: "赛事运营、竞技客户维护与转化",
  frontdesk: "负责客户接待和前台管理",
  operator: "负责内容和数据分析",
};

/* ─── MVP 岗位列表 ─── */

export const MVP_ROLES: WorkbenchRole[] = ["boss", "manager", "assistant_manager", "coach", "frontdesk", "operator"];

/* ─── 模块标签映射 ─── */

export const MODULE_LABELS: Record<string, string> = {
  basic: "基础信息",
  business_goals: "经营目标",
  customer_structure: "客户结构",
  private_domain_groups: "私域群矩阵",
  assistant_system: "助教体系",
  events: "赛事活动",
  commerce_rules: "团购/价格规则",
  equipment: "桌型设备",
  content_style: "内容风格",
};

/* ─── output_package 标签映射 ─── */

const OUTPUT_LABELS: Record<string, string> = {
  moments: "朋友圈",
  group_notice: "群公告",
  private_chat: "私聊话术",
  poster_copy: "海报文案",
  short_video: "短视频配文",
  execution_tips: "执行建议",
  daily_report: "日报",
  activity_plan: "活动方案",
  sop_checklist: "SOP检查表",
  pk_plan: "PK方案",
};

export function getOutputLabels(packages: OutputPackageItem[]): string {
  return packages.map((p) => OUTPUT_LABELS[p] || p).join(" · ");
}
