export const ELECTRON_IPC_CHANNELS = {
  appGetVersion: 'desktop:app:get-version',
  runtimeGetServerUrl: 'desktop:runtime:get-server-url',
  modelConfigurationSummary: 'desktop:model-configuration:summary',
  modelConfigurationSave: 'desktop:model-configuration:save',
  modelConfigurationSetRoute: 'desktop:model-configuration:set-route',
  modelConfigurationRemove: 'desktop:model-configuration:remove',
  nativeAgentStartThread: 'desktop:native-agent:start-thread',
  nativeAgentResumeThread: 'desktop:native-agent:resume-thread',
  nativeAgentReadThread: 'desktop:native-agent:read-thread',
  nativeAgentForkThread: 'desktop:native-agent:fork-thread',
  nativeAgentUpdatePermissionMode: 'desktop:native-agent:update-permission-mode',
  nativeAgentStartTurn: 'desktop:native-agent:start-turn',
  nativeAgentSteerTurn: 'desktop:native-agent:steer-turn',
  nativeAgentInterruptTurn: 'desktop:native-agent:interrupt-turn',
  nativeAgentArchiveThread: 'desktop:native-agent:archive-thread',
  nativeAgentResolveApproval: 'desktop:native-agent:resolve-approval',
  nativeAgentConfigureMcpServer: 'desktop:native-agent:configure-mcp-server',
  nativeAgentRemoveMcpServer: 'desktop:native-agent:remove-mcp-server',
  nativeAgentListMcpServerStatuses: 'desktop:native-agent:list-mcp-server-statuses',
  nativeAgentStartMcpOAuth: 'desktop:native-agent:start-mcp-oauth',
  nativeAgentListSkills: 'desktop:native-agent:list-skills',
  nativeAgentSetSkillEnabled: 'desktop:native-agent:set-skill-enabled',
  nativeAgentListHooks: 'desktop:native-agent:list-hooks',
  nativeAgentListCollaborationModes: 'desktop:native-agent:list-collaboration-modes',
  commandInvoke: 'desktop:command:invoke',
  clipboardReadText: 'desktop:clipboard:read-text',
  clipboardWriteText: 'desktop:clipboard:write-text',
  shellOpen: 'desktop:shell:open',
  shellOpenPath: 'desktop:shell:open-path',
  dialogOpen: 'desktop:dialog:open',
  dialogSave: 'desktop:dialog:save',
  imageSubmitProject: 'desktop:image:submit-project',
  imageStartOperation: 'desktop:image:start-operation',
  imageUpdateUnknownProject: 'desktop:image:update-unknown-project',
  imageSaveOutput: 'desktop:image:save-output',
  videoAddSource: 'desktop:video:add-source',
  videoRender: 'desktop:video:render',
  videoAnalyze: 'desktop:video:analyze',
  updateCheck: 'desktop:update:check',
  updateDownload: 'desktop:update:download',
  updateInstall: 'desktop:update:install',
  updatePrepareInstall: 'desktop:update:prepare-install',
  updateCancelInstall: 'desktop:update:cancel-install',
  updateRelaunch: 'desktop:update:relaunch',
  notificationPermissionState: 'desktop:notification:permission-state',
  notificationRequestPermission: 'desktop:notification:request-permission',
  notificationSend: 'desktop:notification:send',
  notificationActionAck: 'desktop:notification:action-ack',
  windowMinimize: 'desktop:window:minimize',
  windowToggleMaximize: 'desktop:window:toggle-maximize',
  windowClose: 'desktop:window:close',
  windowStartDragging: 'desktop:window:start-dragging',
  windowRequestAttention: 'desktop:window:request-attention',
  windowFocus: 'desktop:window:focus',
  windowIsMaximized: 'desktop:window:is-maximized',
  appModeGet: 'desktop:app-mode:get',
  appModeSet: 'desktop:app-mode:set',
  appModeDetectPortableDir: 'desktop:app-mode:detect-portable-dir',
  appModePrepareRestart: 'desktop:app-mode:prepare-restart',
  appModeRestart: 'desktop:app-mode:restart',
  zoomSet: 'desktop:zoom:set',
} as const

export const ELECTRON_EVENT_CHANNELS = {
  event: 'desktop:event',
  notificationAction: 'desktop:notification:action',
  updateDownloadEvent: 'desktop:update:download-event',
  windowResized: 'desktop:window:resized',
  nativeMenuNavigate: 'desktop:window:native-menu-navigate',
  nativeAgentEvent: 'desktop:native-agent:event',
} as const

export type ElectronIpcChannel = typeof ELECTRON_IPC_CHANNELS[keyof typeof ELECTRON_IPC_CHANNELS]
export type ElectronEventChannel = typeof ELECTRON_EVENT_CHANNELS[keyof typeof ELECTRON_EVENT_CHANNELS]
