export const ELECTRON_IPC_CHANNELS = {
  appGetVersion: 'desktop:app:get-version',
  runtimeGetServerUrl: 'desktop:runtime:get-server-url',
  modelConfigurationSummary: 'desktop:model-configuration:summary',
  modelConfigurationSave: 'desktop:model-configuration:save',
  modelConfigurationSetRoute: 'desktop:model-configuration:set-route',
  modelConfigurationRemove: 'desktop:model-configuration:remove',
  nativeAgentStartThread: 'desktop:native-agent:start-thread',
  nativeAgentResumeThread: 'desktop:native-agent:resume-thread',
  nativeAgentReadThread: 'desktop:native-agent:read-thread',
  nativeAgentForkThread: 'desktop:native-agent:fork-thread',
  nativeAgentUpdatePermissionMode: 'desktop:native-agent:update-permission-mode',
  nativeAgentStartTurn: 'desktop:native-agent:start-turn',
  nativeAgentSteerTurn: 'desktop:native-agent:steer-turn',
  nativeAgentInterruptTurn: 'desktop:native-agent:interrupt-turn',
  nativeAgentArchiveThread: 'desktop:native-agent:archive-thread',
  nativeAgentResolveApproval: 'desktop:native-agent:resolve-approval',
  commandInvoke: 'desktop:command:invoke',
  clipboardReadText: 'desktop:clipboard:read-text',
  clipboardWriteText: 'desktop:clipboard:write-text',
  shellOpen: 'desktop:shell:open',
  shellOpenPath: 'desktop:shell:open-path',
  dialogOpen: 'desktop:dialog:open',
  dialogSave: 'desktop:dialog:save',
  imageSubmitProject: 'desktop:image:submit-project',
  imageStartOperation: 'desktop:image:start-operation',
  imageUpdateUnknownProject: 'desktop:image:update-unknown-project',
  imageSaveOutput: 'desktop:image:save-output',
  videoAddSource: 'desktop:video:add-source',
  videoRender: 'desktop:video:render',
  videoAnalyze: 'desktop:video:analyze',
  browserStatus: 'desktop:browser:status',
  browserInstall: 'desktop:browser:install',
  browserListActions: 'desktop:browser:list-actions',
  browserResolveAction: 'desktop:browser:resolve-action',
  updateCheck: 'desktop:update:check',
  updateDownload: 'desktop:update:download',
  updateInstall: 'desktop:update:install',
  updatePrepareInstall: 'desktop:update:prepare-install',
  updateCancelInstall: 'desktop:update:cancel-install',
  updateRelaunch: 'desktop:update:relaunch',
  notificationPermissionState: 'desktop:notification:permission-state',
  notificationRequestPermission: 'desktop:notification:request-permission',
  notificationSend: 'desktop:notification:send',
  notificationActionAck: 'desktop:notification:action-ack',
  windowMinimize: 'desktop:window:minimize',
  windowToggleMaximize: 'desktop:window:toggle-maximize',
  windowClose: 'desktop:window:close',
  windowStartDragging: 'desktop:window:start-dragging',
  windowRequestAttention: 'desktop:window:request-attention',
  windowFocus: 'desktop:window:focus',
  windowIsMaximized: 'desktop:window:is-maximized',
  windowOpenProductTask: 'desktop:window:open-product-task',
  terminalSpawn: 'desktop:terminal:spawn',
  terminalWrite: 'desktop:terminal:write',
  terminalResize: 'desktop:terminal:resize',
  terminalKill: 'desktop:terminal:kill',
  terminalGetBashPath: 'desktop:terminal:get-bash-path',
  terminalSetBashPath: 'desktop:terminal:set-bash-path',
  previewOpen: 'desktop:preview:open',
  previewNavigate: 'desktop:preview:navigate',
  previewSetBounds: 'desktop:preview:set-bounds',
  previewSetVisible: 'desktop:preview:set-visible',
  previewSetZoom: 'desktop:preview:set-zoom',
  previewClose: 'desktop:preview:close',
  previewMessage: 'desktop:preview:message',
  appModeGet: 'desktop:app-mode:get',
  appModeSet: 'desktop:app-mode:set',
  appModeDetectPortableDir: 'desktop:app-mode:detect-portable-dir',
  appModePrepareRestart: 'desktop:app-mode:prepare-restart',
  appModeRestart: 'desktop:app-mode:restart',
  zoomSet: 'desktop:zoom:set',
} as const

export const ELECTRON_EVENT_CHANNELS = {
  event: 'desktop:event',
  webviewDragDrop: 'desktop:webview:drag-drop',
  notificationAction: 'desktop:notification:action',
  updateDownloadEvent: 'desktop:update:download-event',
  windowResized: 'desktop:window:resized',
  nativeMenuNavigate: 'desktop:window:native-menu-navigate',
  terminalOutput: 'desktop:terminal:output',
  terminalExit: 'desktop:terminal:exit',
  previewEvent: 'desktop:preview:event',
  nativeAgentEvent: 'desktop:native-agent:event',
} as const

export const ELECTRON_INTERNAL_CHANNELS = {
  previewMessageFromView: 'desktop:preview:message-from-view',
} as const

export type ElectronIpcChannel = typeof ELECTRON_IPC_CHANNELS[keyof typeof ELECTRON_IPC_CHANNELS]
export type ElectronEventChannel = typeof ELECTRON_EVENT_CHANNELS[keyof typeof ELECTRON_EVENT_CHANNELS]
export type ElectronInternalChannel = typeof ELECTRON_INTERNAL_CHANNELS[keyof typeof ELECTRON_INTERNAL_CHANNELS]
