import { expect, test } from 'bun:test'
import * as fs from 'node:fs/promises'
import * as os from 'node:os'
import * as path from 'node:path'
import { ProductTaskService } from '../product/taskService.js'
import { CoreOperationTerminalError } from '../product/coreOperationBridge.js'
import { ProductTaskAuthorityRepository } from '../product/authorityRepository.js'

test('authoritative create prepares before bridge, never writes legacy, and replays after finalize crash', async () => { const root = await fs.mkdtemp(path.join(os.tmpdir(), 'authority-create-')); const legacy = path.join(root, 'product-tasks.json'); await fs.writeFile(legacy, '{"version":4,"tasks":{}}'); const before = await fs.readFile(legacy); const authority = path.join(root, 'product-task-authority.v1.json'); let calls = 0; let observedPrepared = false; const bridge = { ensureCreate: async () => { calls++; observedPrepared = Boolean((await fs.readFile(authority, 'utf8')).includes('"prepared"')); return { coreSessionId: 'private-core' } } }; const service = new ProductTaskService({ storagePath: legacy }); const input = { workDir: root, title: 'hello', expected_revision: 0, client_operation_id: 'op-create' }; await expect(service.createTaskAuthoritatively(input, { authorityPath: authority, bridge, afterEnsure: () => { throw new Error('crash-after-bridge') } })).rejects.toThrow('crash-after-bridge'); const result = await new ProductTaskService({ storagePath: legacy }).createTaskAuthoritatively(input, { authorityPath: authority, bridge }); expect(observedPrepared).toBeTrue(); expect(calls).toBe(2); expect(result.receipt.outcome).toBe('accepted'); expect(JSON.stringify(result.task)).not.toContain('private-core'); expect(await fs.readFile(legacy)).toEqual(before) })
test('authoritative create rejects input reuse conflict', async () => { const root = await fs.mkdtemp(path.join(os.tmpdir(), 'authority-create-conflict-')); const authority = path.join(root, 'product-task-authority.v1.json'); const bridge = { ensureCreate: async () => ({ coreSessionId: 'private' }) }; const s = new ProductTaskService(); await s.createTaskAuthoritatively({ workDir: root, expected_revision: 0, client_operation_id: 'same' }, { authorityPath: authority, bridge }); const second = await s.createTaskAuthoritatively({ workDir: `${root}/other`, expected_revision: 0, client_operation_id: 'same' }, { authorityPath: authority, bridge }); expect(second.receipt.outcome).toBe('conflict') })
test('legacy task projection is one-time, byte-preserving, and starts at revision one', async () => { const root = await fs.mkdtemp(path.join(os.tmpdir(), 'authority-projection-')); const legacy = path.join(root, 'product-tasks.json'); const body = '{"version":4,"tasks":{"task-legacy":{"coreSessionId":"private-core","title":"legacy","lifecycle":"active","kind":"main","createdAt":"2026-01-01T00:00:00.000Z","updatedAt":"2026-01-01T00:00:00.000Z"}},"sideTasks":{"side-1":{"parentTaskId":"task-parent"}}}'; await fs.writeFile(legacy, body); const authority = path.join(root, 'authority.json'); const service = new ProductTaskService({ storagePath: legacy }); const first = await service.ensureAuthorityProjectionForLegacyTask('task-legacy', { authorityPath: authority }); const again = await service.ensureAuthorityProjectionForLegacyTask('task-legacy', { authorityPath: authority }); expect(first.revision).toBe(1); expect(again.revision).toBe(1); expect(await fs.readFile(legacy, 'utf8')).toBe(body); await fs.writeFile(legacy, body.replace('"title":"legacy"','"title":"changed"')); await expect(service.ensureAuthorityProjectionForLegacyTask('task-legacy', { authorityPath: authority })).rejects.toThrow('LEGACY_SOURCE_CHANGED') })
test('legacy projection serializes concurrent initialization and supports CAS branch lifecycle', async () => { const root = await fs.mkdtemp(path.join(os.tmpdir(), 'authority-projection-cas-')); const legacy = path.join(root, 'product-tasks.json'); const body = '{"version":4,"tasks":{"task-parent":{"coreSessionId":"private-core","title":"legacy","lifecycle":"active","kind":"main","createdAt":"2026-01-01T00:00:00.000Z","updatedAt":"2026-01-01T00:00:00.000Z"}},"sideTasks":{"side-1":{"parentTaskId":"task-parent"}}}'; await fs.writeFile(legacy, body); const authority = path.join(root, 'authority.json'); const service = new ProductTaskService({ storagePath: legacy }); const [left, right] = await Promise.all([service.ensureAuthorityProjectionForLegacyTask('task-parent', { authorityPath: authority }), service.ensureAuthorityProjectionForLegacyTask('task-parent', { authorityPath: authority })]); expect([left.revision, right.revision]).toEqual([1, 1]); const pin = await service.mutateTaskAuthoritatively({ taskId: 'task-parent', patch: { pinned: true }, expected_revision: 1, client_operation_id: 'pin' }, { authorityPath: authority }); expect(pin.receipt.outcome).toBe('accepted'); const stale = await service.mutateTaskAuthoritatively({ taskId: 'task-parent', patch: { pinned: false }, expected_revision: 1, client_operation_id: 'stale' }, { authorityPath: authority }); expect(stale.receipt.outcome).toBe('conflict'); const bridge = { ensureBranch: async () => ({ coreSessionId: 'private-child' }) }; const continued = await service.continueTaskAuthoritatively({ taskId: 'task-parent', expected_revision: pin.receipt.revision, client_operation_id: 'continue', canonical_input: '{}' }, { authorityPath: authority, bridge }); expect(continued.outcome).toBe('accepted'); const side = await service.createSideTaskAuthoritatively({ taskId: 'task-parent', sideTaskId: 'task-side', expected_revision: continued.revision, client_operation_id: 'side', canonical_input: '{}' }, { authorityPath: authority, bridge }); expect(side.outcome).toBe('accepted'); const closed = await service.closeSideTaskAuthoritatively({ taskId: 'task-parent', sideTaskId: 'task-side', expected_revision: side.revision, client_operation_id: 'close', canonical_input: '{}' }, { authorityPath: authority }); expect(closed.outcome).toBe('accepted'); expect(await fs.readFile(legacy, 'utf8')).toBe(body) })


test('terminal Core create failure is finalized as a durable rejected receipt', async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'authority-rejected-'))
  const authority = path.join(root, 'authority.json')
  const service = new ProductTaskService()
  const result = await service.createTaskAuthoritatively({ workDir: root, expected_revision: 0, client_operation_id: 'terminal-create' }, { authorityPath: authority, bridge: { ensureCreate: async () => { throw new CoreOperationTerminalError('CORE_OPERATION_INPUT_INVALID', 'bad') } } })
  expect(result.receipt.outcome).toBe('rejected')
  const persisted = await new ProductTaskAuthorityRepository(authority).read()
  expect(persisted.prepared['terminal-create']).toBeUndefined()
  expect(persisted.receipts['terminal-create']?.outcome).toBe('rejected')
})
