import { expect, test } from 'bun:test'
import * as fs from 'node:fs/promises'
import * as os from 'node:os'
import * as path from 'node:path'
import { ProductTaskAuthorityRepository, readLegacyProductTasks } from '../product/authorityRepository.js'

async function repo() { const root = await fs.mkdtemp(path.join(os.tmpdir(), 'product-authority-service-')); return new ProductTaskAuthorityRepository(path.join(root, 'product-task-authority.v1.json')) }
test('prepared intent is durable, idempotent, and finalizes one receipt', async () => { const r = await repo(); const intent = { client_operation_id: 'op-1', product_task_id: 'task-1', kind: 'create' as const, canonical_input: '{"title":"x"}', expected_revision: 0 }; expect((await r.reserve(intent)).duplicate).toBeFalse(); expect((await r.reserve(intent)).duplicate).toBeTrue(); await r.finalize('op-1', { client_operation_id: 'op-1', expected_revision: 0, outcome: 'accepted', revision: 1 }, { task: { id: 'task-1', projectId: '', directoryId: '', workDir: '', title: 'x', lifecycle: 'active', kind: 'main', createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z', worktreeState: 'not_requested', actions: [] }, binding: { coreSessionId: 'private' } } ); const f = await r.read(); expect(f.prepared['op-1']).toBeUndefined(); expect(f.receipts['op-1'].outcome).toBe('accepted'); expect(f.tasks['task-1']).toEqual({ task: { id: 'task-1', projectId: '', directoryId: '', workDir: '', title: 'x', lifecycle: 'active', kind: 'main', createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z', worktreeState: 'not_requested', actions: [] }, binding: { coreSessionId: 'private' } }) })
test('CAS has exactly one winner', async () => { const r = await repo(); const results = await Promise.allSettled([r.reserve({ client_operation_id: 'op-a', product_task_id: 'a', kind: 'create', canonical_input: '{}', expected_revision: 0 }), r.reserve({ client_operation_id: 'op-b', product_task_id: 'b', kind: 'create', canonical_input: '{}', expected_revision: 0 })]); expect(results.filter(x => x.status === 'fulfilled')).toHaveLength(1); expect(results.filter(x => x.status === 'rejected')).toHaveLength(1) })
test('legacy provenance rejects changed source bytes', async () => { const root = await fs.mkdtemp(path.join(os.tmpdir(), 'product-authority-legacy-')); const source = path.join(root, 'product-tasks.json'); await fs.writeFile(source, '{"version":4,"tasks":{"task":{"coreSessionId":"private"}}}'); const r = new ProductTaskAuthorityRepository(path.join(root, 'product-task-authority.v1.json')); await r.verifyLegacy('task', await readLegacyProductTasks(source)); await fs.writeFile(source, '{"version":4,"tasks":{"task":{"coreSessionId":"changed"}}}'); await expect(r.verifyLegacy('task', await readLegacyProductTasks(source))).rejects.toThrow('LEGACY_SOURCE_CHANGED') })
test('rename mirror states do not alter accepted receipt', async () => { const r = await repo(); await r.reserve({ client_operation_id: 'rename-1', product_task_id: 'task-1', kind: 'close', canonical_input: '{}', expected_revision: 0 }); await r.finalize('rename-1', { client_operation_id: 'rename-1', expected_revision: 0, outcome: 'accepted', revision: 1 }); await r.setOutbox('rename-1', 'pending'); await r.setOutbox('rename-1', 'failed', 'CORE_OPERATION_TERMINAL_FAILURE'); const f = await r.read(); expect(f.receipts['rename-1'].outcome).toBe('accepted'); expect(f.outbox['rename-1'].state).toBe('failed') })
test('branch replay retains one prepared intent and rejects changed input', async () => { const r = await repo(); const intent = { client_operation_id: 'branch-1', product_task_id: 'task-child', kind: 'branch' as const, canonical_input: '{"parent":"task-parent"}', expected_revision: 0 }; await r.reserve(intent); expect((await r.reserve(intent)).duplicate).toBeTrue(); await expect(r.reserve({ ...intent, canonical_input: '{"parent":"different"}' })).rejects.toThrow('AUTHORITY_CONFLICT'); const final = await r.finalize(intent.client_operation_id, { client_operation_id: intent.client_operation_id, expected_revision: 0, outcome: 'accepted', revision: 0 }, { task: { id: 'task-child', projectId: '', directoryId: '', workDir: '', title: '', lifecycle: 'active', kind: 'continuation', parentTaskId: 'task-parent', createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z', worktreeState: 'not_requested', actions: [] }, binding: { coreSessionId: 'private' } }); expect(final.receipts[intent.client_operation_id]?.revision).toBe(final.revision); expect(JSON.stringify(final.tasks['task-child'])).toContain('private') })
