import { createHash, createHmac } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { Readable } from 'node:stream'
import { expect, test } from 'bun:test'
import { OssObjectStore } from '../../video-media-relay/objectStore.ts'

const require = createRequire(import.meta.url)
const officialV4 = require('../node_modules/ali-oss/lib/common/signUtils.js') as {
  getCanonicalRequest(method: string, request: { headers: Record<string, string>; queries?: Record<string, string> }, bucket: string, object: string, additionalHeaders: string[]): string
  getStringToSign(region: string, timestamp: string, canonicalRequest: string, product: string): string
  getSignatureV4(secret: string, date: string, region: string, stringToSign: string, product: string): string
}

const hash = (bytes: Uint8Array) => `sha256:${createHash('sha256').update(bytes).digest('hex')}`
const credentials = { endpoint: 'oss-cn-beijing.aliyuncs.com', bucket: 'bb-video-media-contract', accessKeyId: 'LTAIexampleaccesskey', accessKeySecret: 'example-access-key-secret', region: 'oss-cn-beijing' }

test('production visual smoke fixture satisfies the model minimum dimensions', () => {
  const source = readFileSync(new URL('../../deploy/production/video-media-smoke.ts', import.meta.url), 'utf8')
  const match = /const image = Buffer\.from\('([^']+)', 'base64'\)/.exec(source)
  expect(match?.[1]).toBeDefined()
  const image = Buffer.from(match![1]!, 'base64')
  expect(image.subarray(1, 4).toString('ascii')).toBe('PNG')
  expect(image.readUInt32BE(16)).toBeGreaterThan(10)
  expect(image.readUInt32BE(20)).toBeGreaterThan(10)
})

test('official OSS V4 documented signing vector includes the bucket in Canonical URI', () => {
  // Values and expected signature are Alibaba Cloud's published PutObject V4
  // example, not a value generated by the Relay implementation.
  const headers = {
    'content-disposition': 'attachment',
    'content-length': '3',
    'content-md5': 'ICy5YqxZB1uWSwcVLSNLcA==',
    'content-type': 'text/plain',
    'x-oss-content-sha256': 'UNSIGNED-PAYLOAD',
    'x-oss-date': '20250411T064124Z',
  }
  const canonical = officialV4.getCanonicalRequest('PUT', { headers }, 'examplebucket', 'exampleobject', ['content-disposition', 'content-length'])
  expect(canonical).toBe(`PUT\n/examplebucket/exampleobject\n\ncontent-disposition:attachment\ncontent-length:3\ncontent-md5:ICy5YqxZB1uWSwcVLSNLcA==\ncontent-type:text/plain\nx-oss-content-sha256:UNSIGNED-PAYLOAD\nx-oss-date:20250411T064124Z\n\ncontent-disposition;content-length\nUNSIGNED-PAYLOAD`)
  const stringToSign = officialV4.getStringToSign('cn-hangzhou', '20250411T064124Z', canonical, 'oss')
  expect(stringToSign).toBe('OSS4-HMAC-SHA256\n20250411T064124Z\n20250411/cn-hangzhou/oss/aliyun_v4_request\nc46d96390bdbc2d739ac9363293ae9d710b14e48081fcb22cd8ad54b63136eca')
  const documentedSigningKey = Buffer.from('3543b7686e65eda71e5e5ca19d548d78423c37e8ddba4dc9d83f90228b457c76', 'hex')
  expect(createHmac('sha256', documentedSigningKey).update(stringToSign).digest('hex')).toBe('053edbf550ebd239b32a9cdfd93b0b2b3f2d223083aa61f75e9ac16856d61f23')
})

test('OSS response contract reads real HTTP headers, streams bytes, and uses ali-oss pagination arguments', async () => {
  const calls: Array<Record<string, unknown>> = []
  const signedCalls: Array<{ method: string; key: string; additionalHeaders: string[] | undefined }> = []
  const resultWrites: Array<{ key: string; body: Uint8Array; options: Record<string, unknown> }> = []
  const bytes = new TextEncoder().encode('actual OSS body')
  const client = {
    async signatureUrlV4(method: string, _expires: number, _request: unknown, key: string, additionalHeaders?: string[]) { signedCalls.push({ method, key, additionalHeaders }); return `https://bb-video-media-contract.oss-cn-beijing.aliyuncs.com/${key}?x-oss-signature-version=OSS4-HMAC-SHA256` },
    async head() { return { res: { headers: { 'content-type': 'video/mp4; charset=binary' } } } },
    async getStream() { return { stream: Readable.from([bytes]) } },
    async putStream(key: string, stream: Readable, options: Record<string, unknown>) {
      const chunks: Uint8Array[] = []
      for await (const chunk of stream) {
        expect(typeof chunk).not.toBe('number')
        chunks.push(Buffer.from(chunk))
      }
      resultWrites.push({ key, body: Buffer.concat(chunks), options })
    }, async delete() {},
    async listParts(_name: string, _uploadId: string, query: Record<string, unknown>) {
      calls.push(query)
      return query['part-number-marker'] ? { isTruncated: false, parts: [{ PartNumber: '1001', ETag: 'etag-1001' }] } : { isTruncated: true, nextPartNumberMarker: '1000', parts: [{ PartNumber: '1', ETag: 'etag-1' }] }
    },
    async listUploads() { return { isTruncated: false, uploads: [] } },
    async abortMultipartUpload() {}, async completeMultipartUpload() {}, async initMultipartUpload() { return { uploadId: 'upload-123' } },
  }
  const store = new OssObjectStore({ ...credentials, client })
  const signed = await store.createPutUrl({ leaseId: 'lease_12345678', hash: hash(bytes), byteSize: bytes.byteLength, contentType: 'video/mp4', expiresAt: new Date(Date.now() + 60_000).toISOString() })
  expect(new URL(signed.put_url).searchParams.get('x-oss-signature-version')).toBe('OSS4-HMAC-SHA256')
  expect(signedCalls).toEqual([{ method: 'PUT', key: 'video-media/input/lease_12345678', additionalHeaders: ['content-type', 'if-none-match', 'x-oss-meta-sha256', 'x-oss-meta-size'] }])
  expect(await store.listMultipartParts({ leaseId: 'lease_12345678', uploadId: 'upload-123' })).toEqual([{ part_number: 1, etag: 'etag-1' }, { part_number: 1001, etag: 'etag-1001' }])
  expect(calls).toEqual([{ 'max-parts': 1000 }, { 'max-parts': 1000, 'part-number-marker': 1000 }])
  expect(await store.head('lease_12345678')).toEqual({ byte_size: bytes.byteLength, content_hash: hash(bytes), content_type: 'video/mp4' })
  await store.putResult({ objectRef: 'result_12345678', body: bytes, contentHash: hash(bytes), contentType: 'application/json' })
  expect(resultWrites).toEqual([{
    key: 'video-media/result/result_12345678', body: bytes,
    options: { contentLength: bytes.byteLength, mime: 'application/json', meta: { sha256: hash(bytes), size: String(bytes.byteLength) }, headers: { 'If-None-Match': '*' } },
  }])
})

const live = process.env.VIDEO_MEDIA_OSS_CONTRACT === '1'
const liveTest = live ? test : test.skip
liveTest('OSS live contract creates, lists, completes, HEADs, streams and cleans a V4 multipart object', async () => {
  const endpoint = process.env.VIDEO_MEDIA_OSS_ENDPOINT!; const bucket = process.env.VIDEO_MEDIA_OSS_BUCKET!; const accessKeyId = process.env.VIDEO_MEDIA_OSS_ACCESS_KEY_ID!; const accessKeySecret = process.env.VIDEO_MEDIA_OSS_ACCESS_KEY_SECRET!
  if (![endpoint, bucket, accessKeyId, accessKeySecret].every(Boolean)) throw new Error('live OSS contract requires VIDEO_MEDIA_OSS_ENDPOINT, VIDEO_MEDIA_OSS_BUCKET and dedicated RAM credentials')
  const store = new OssObjectStore({ endpoint, bucket, accessKeyId, accessKeySecret, region: 'oss-cn-beijing' })
  const leaseId = `lease_contract_${crypto.randomUUID().replaceAll('-', '')}`; const body = new Uint8Array(2 * 1024 * 1024); body.fill(7)
  let uploadId: string | undefined; let completed = false
  try {
    const upload = await store.createMultipartUpload({ leaseId, hash: hash(body), byteSize: body.byteLength, contentType: 'application/octet-stream' }); uploadId = upload.uploadId
    const parts: Array<{ part_number: number; etag: string }> = []
    for (const partNumber of [1, 2]) {
      const signed = await store.createMultipartPartPutUrl({ leaseId, uploadId, partNumber, expiresAt: new Date(Date.now() + 60_000).toISOString() })
      const response = await fetch(signed.put_url, { method: 'PUT', headers: signed.required_headers, body: body.subarray((partNumber - 1) * 1024 * 1024, partNumber * 1024 * 1024) })
      if (!response.ok || !response.headers.get('etag')) throw new Error(`live OSS part ${partNumber} failed`)
      parts.push({ part_number: partNumber, etag: response.headers.get('etag')! })
    }
    expect(await store.listMultipartParts({ leaseId, uploadId })).toEqual(parts)
    await store.completeMultipartUpload({ leaseId, uploadId, parts }); completed = true
    expect(await store.head(leaseId)).toEqual({ byte_size: body.byteLength, content_hash: hash(body), content_type: 'application/octet-stream' })
  } finally {
    if (uploadId && !completed) await store.abortMultipartUpload({ leaseId, uploadId })
    await store.delete(leaseId)
  }
})
