"""共享的场景-角色映射表，避免 content_service.py 和 stream.py 重复定义"""

SCENARIO_ROLE_MAP = {
    "groupbuy_to_private": "frontdesk",
    "assistant_promo": "assistant_manager",
    "partner_match": "coach",
    "tournament": "coach",
    "old_customer_recall": "manager",
    "assistant_outreach": "assistant_manager",
    "assistant_booking": "assistant_manager",
    "assistant_supervision": "assistant_manager",
    "assistant_difficult": "assistant_manager",
    "member_assistant_notice": "assistant_manager",
    "daily_report": None,  # None = 使用请求中的 role 作为 fallback
    "performance_template": "assistant_manager",
    "daily_task_list": None,  # None = 使用请求中的 role 作为 fallback
    "vip_maintenance": "manager",
    "group_content": "operator",
    "short_video": "operator",
    "complaint_handling": "frontdesk",
    "frontdesk_sop": "frontdesk",
    "tournament_signup": "coach",
    "tournament_report": "coach",
    "qiangyi_battle": "coach",
    "review_guidance": "coach",
    "cart_promotion": "frontdesk",
    "opening_event": "operator",
    "recruitment": "assistant_manager",
    "training_exam": "assistant_manager",
    "diagnosis_tool": "boss",
    "coaching_promo": "coach",
    "competition_customer": "coach",
    "empty_table_promo": "frontdesk",
    "departure_followup": "frontdesk",
    "customer_group_guide": "frontdesk",
    "opening_closing_sop": "frontdesk",
    "equipment_management": "frontdesk",
    "store_atmosphere": "operator",
    "poster_copy": "operator",
    "sports_event_watching": "manager",
    "staff_birthday": "manager",
    "hygiene_check": "frontdesk",
    "champion_poster": "coach",
    "tournament_rules": "coach",
    "monthly_report": "boss",
    "activity_direction": "boss",
    "business_strategy": "boss",
    "table_content_plan": "operator",
    "game_recommend": "coach",
    "ip_cooperation": "assistant_manager",
    "review_meeting": "manager",
    "holiday_promo": "operator",
    "new_store_opening": "operator",
    "member_day": "operator",
    # 按 PPT 岗位工作内容补齐（2026-06-16）
    "purchase_plan": "frontdesk",
    "frontdesk_onboarding": "frontdesk",
    "patrol_safety_check": "frontdesk",
    "shift_schedule": "frontdesk",
    "phased_goal_plan": "manager",
    "team_building_plan": "manager",
    "four_data_review": "manager",
    "coach_outreach": "coach",
    "cross_industry_alliance": "operator",
    "referral_program": "operator",
    "ground_promotion": "operator",
    "theme_night": "operator",
}
